# -*- coding: utf-8 -*-
{
    'name': "MetroERP IRAS",
    'version': '1.1',
    'author': 'Metro Group',
    'category': 'All',
    'summary': 'IRAS',
    'description': "",
    'website': 'https://metrogroup.solutions/',
    'depends': [
                'base',
                'account',
                'l10n_sg',
                'metroerp_customizations',
                'base_import',
                'ks_dynamic_financial_report'
                ],
    'data': [
        "security/ir.model.access.csv",
        "security/groups.xml",
        "security/security.xml",
        "views/res_partner.xml",
        "views/menus.xml",
        "views/res_config_settings.xml",
        "views/gst_returns_f5f8.xml",
        "views/gst_returns_f7.xml",
        "views/account_tax_view.xml",
        "views/form_cs_view.xml",
        "views/draft_form_cs.xml",
        "views/ack_form_cs.xml",
        "views/corppass_logs.xml",
        "views/account_account_view.xml",
        "views/iras_coa_mapping_view.xml",
        "views/gst_f5_auto_schedule_view.xml",
        "wizard/gst_returns_prompt_wizard_view.xml",
        "wizard/formcs_bulk_import.xml",
        "wizard/formcs_part_b_check.xml",
        "data/cron_data.xml",
        "data/mail_data.xml",
        "data/data.xml",
        "views/view_acknowledgement_template.xml",
        "views/iras_default_accounts_mapping.xml",
        "views/account_chart_templates_inherited_views.xml",
        "data/paper_format_data.xml",
        "report/gst_returns_f5f8_report.xml",
    ],
    # 'qweb': ['static/src/xml/base_import.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
