# -*- coding: utf-8 -*-
{
    'name': 'Singapore PEPPOL Invoices Integration - DataPost',
    'summary': "Singapore PEPPOL Invoices Integration using the services offered by DataPost.",
    'author': 'Metro Group Solutions',
    'website': 'https://metrogroup.solutions/',
    'category': 'Accounting & Finance',
    'version': '14.0.0.1.0',
    'depends': [
        'account',
        'base_ubl',
        'purchase',
        'sale',
        'l10n_sg',
        'sale_management',
        'contacts',
'metroerp_send_receive_money',
'metro_invoice_user',
    ],
    'data': [
        "security/security.xml",
        "security/ir.model.access.csv",
        "security/ir_rule.xml",
        "views/res_partner.xml",
        "views/res_company.xml",
        "views/menus.xml",
        "views/account_move.xml",
        "views/res_config_settings.xml",
        "views/peppol_queue_out_views.xml",
        "views/peppol_access_point_view.xml",
        "views/peppol_queue_in_view.xml",
        "views/invoice_responses_queue_out.xml",
        "views/purchase_order_view.xml",
        "views/peppol_partner_autocomplete_assets.xml",
        "views/incoming_failed_logs_views.xml",
        "views/order_queue_out_views.xml",
        "views/order_queue_in_views.xml",
        "views/account_journal_inherit.xml",
        "views/sale_order_view.xml",
        "views/invoice_responses_queue_in.xml",
        "data/ir_cron_data.xml",
        "data/mail_template.xml",
        "data/ir_config_parameter.xml",
        "data/ir_sequence.xml",
        "data/clarification_codes.xml",
        "data/unece_category_code_purchase.xml",
        "wizard/peppol_warning_wizard.xml",
        "wizard/peppol_manual_send_wizard_view.xml",
        "wizard/invoice_response_prefill_status.xml",
        "wizard/api_search_view.xml",
        "report/peppol_invoice_report.xml",
        "views/c5_activation_views.xml",
        # "views/peppol_queue_c5_in_views.xml",
        "views/peppol_queue_c5_out_views.xml",
        "views/b2c_outgoing_invoices_view.xml",
        "views/pcp_outgoing_invoices_views.xml",
        "wizard/peppol_manual_send_payment_wizard_views.xml",
        "views/account_payment_view.xml",
        "views/order_responses_queue_in.xml",
        "views/order_responses_queue_out.xml",
        "views/order_cancel_queue_out_views.xml",
        "views/order_change_queue_out_views.xml",
        "views/order_balance_queue_out_views.xml",
        "views/order_cancel_in_views.xml",
        "views/order_change_in_views.xml",
        "views/order_balance_in_views.xml",
        "views/order_cancel_advance_responses_queue_out.xml",
        "views/order_cancel_responses_queue_in.xml",
        "views/order_change_responses_queue_out.xml",
        "views/order_balance_responses_queue_out.xml",
        "views/order_change_responses_queue_in.xml",
        "views/order_balance_responses_queue_in.xml",
        "wizard/order_response_prefill_status.xml",
        "wizard/order_advance_response_prefill_status.xml",
        "wizard/order_reason_note_wizard.xml",
        "views/uom_code.xml",
        "report/peppol_c5_invoice_report.xml",
        "views/ministries_statuary_boards.xml",

    ],
	'qweb': [
        'static/src/xml/partner_autocomplete.xml',
        'static/src/xml/search_kanban_view.xml',
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    'post_init_hook': '_pre_init_peppol_id_scheme',
}
