# -*- coding: utf-8 -*-
{
    'name': "MetroERP  Invoice User",
    'version': '1.2.1',
    'author': 'Metro Group',
    'category': 'All',
    'summary': 'MetroERP Invoice User',
    'description': "",
    'website': 'https://metrogroup.solutions/',
    'depends': [
                'base',
                'product',
                'account',
                'om_account_followup',
                'om_account_bank_statement_import',
                'om_account_asset',
                'sale',
                'purchase',
                'contacts',
                'om_account_followup',
                'accounting_pdf_reports',
                'metroerp_iras',
                'ks_dynamic_financial_report',
                ],
    'data': [
        
        'security/res_group.xml',
        'security/ir.model.access.csv',
        'security/ir_model_access.xml',
        # 'security/ir_rule.xml',
        'data/data.xml',
        'views/menu.xml',
        'views/account_move_views.xml',
        'views/account_journal_views.xml',
        'views/account_payment_views.xml',
        'views/account_res_partner_views.xml',
        'views/account_invoice_portal_views.xml',
        'views/account_cash_rounding_views.xml',
        'views/res_partner_views.xml',
        'wizard/invoice_popup_wizard.xml',
        'views/templates.xml',
        'wizard/followup_wizard_inherit.xml',


    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
