# -*- coding: utf-8 -*-
{
    'name': "MetroERP CRM Enhancement",
    'version': '1.0',
    'author': 'Metro Group',
    'category': 'Sales/CRM',
    'summary': 'MetroERP CRM Enhancement',
    'description': "",
    'website': 'https://metrogroup.solutions/',
    'depends': [
        'base',
        'mail',
        'sales_team',
        'crm',
        'crm_iap_lead',
        'metroerp_customizations',
        ],
    'data': [
        'security/res_groups.xml',
        'security/ir_rule.xml',
        'data/data.xml',
        'views/templates.xml',
        'security/ir.model.access.csv',
        'views/crm_stage_views.xml',
        'views/crm_lost_reson_view.xml',
        'views/crm_iap_lead_mining_request_view.xml',
        'views/crm_recurring_plan_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_users.xml',
        'views/res_partner.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,    
}
