# -*- coding: utf-8 -*-
{
    'name': "MetroERP SAAS Customizations",
    'version': '1.2.1',
    'author': 'Metro Group',
    'category': 'All',
    'summary': 'MetroERP SAAS Customizations',
    'description': "",
    'website': 'https://metrogroup.solutions/',
    'depends': [
                'base',
                'mail',
                'fetchmail',
                'snailmail',
                'sms',
                'iap',
                'web_tour',
                'resource',
                'auth_signup',
                'web',
                'mail',
                'portal',
                'mail_bot',
                'account',
                'digest',
                'l10n_sg',
                'purchase',
                'base_import',
                'digest',
                'purchase_stock',
                'sale',
                'contacts',
                'stock',
                'base_setup',
                'metroerp_customizations',
                'muk_web_theme',
                'accounting_pdf_reports',
                'ks_custom_report_layouts',
                'om_account_accountant',
                'ks_dynamic_financial_report',
                'om_recurring_payments',
                'point_of_sale'
                ],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'views/res_config_settings.xml',
        'views/customized_report.xml',
        'views/account_type.xml',
        'views/account_tag.xml',
        'views/ks_dynamic_financial_report.xml',
        'security/ir_rule.xml',
        'wizard/product_change_uom_view.xml',
        'views/product_template_views.xml'
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
