# -*- coding: utf-8 -*-
{
    'name': "MetroERP SAAS Customizations",
    'version': '1.2.1',
    'author': 'Metro Group',
    'category': 'All',
    'summary': 'MetroERP SAAS Customizations',
    'description': "",
    'website': 'https://metrogroup.solutions/',
    'depends': [
                'base',
                'web',
                'account',
                'l10n_sg',
                'purchase',
                'sale',
                'stock',
                'base_setup',
                'metroerp_customizations',
                'accounting_pdf_reports',
                'ks_custom_report_layouts',
                'om_account_accountant',
                'ks_dynamic_financial_report',
                'om_recurring_payments',
                'point_of_sale',
                'metroerp_pos',
                'metroerp_crm_enhancement',
            ],
    'data': [
        'data/data.xml',
        'views/res_config_settings.xml',
        'views/customized_report.xml',
        'views/account_type.xml',
        'views/account_tag.xml',
        'views/ks_dynamic_financial_report.xml',
        'security/ir_rule.xml',
        'wizard/product_change_uom_view.xml',
        'views/product_template_views.xml',
        'views/res_company.xml',
        'views/res_users.xml',
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'views/templates.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
