# -*- coding: utf-8 -*-
{
    'name': "Metro Security Management",
    'version': '1.0',
    'author': 'Metro Group',
    'category': 'Security Management/Security',
    'summary': 'Comprehensive solution for managing security operations, visitor tracking, and access control.',
    'description': '''The Metro Security Management module offers a robust platform for managing security activities 
    including visitor check-ins, vehicle management, gate control, and access logs. Designed to streamline security processes, this module ensures efficient and secure operations for businesses.''',
    'website': 'https://metrogroup.solutions/',
    'depends': ['base','mail','portal','contacts','web'],
    'data': [
        'security/res_group.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/ir_sequence_data.xml',
        'data/paper_format.xml',
        'data/visitor_data.xml',
        'data/qr_code_email_template.xml',
        'views/templates.xml',
        'views/security_contract_views.xml',
        'views/security_location_views.xml',
        'views/security_contract_checkpoint_views.xml',
        'views/security_responses_views.xml',
        'views/visitor_details_views.xml',
        'views/visitor_category_views.xml',
        'views/visitor_type_views.xml',
        'views/block_location_views.xml',
        'wizard/fsm_location_builder_wizard.xml',
        'wizard/fsm_location_level.xml',
        'wizard/whatsup_wizard.xml',
        'views/ic_number_views.xml',
        'views/security_person_views.xml',
        'views/block_list_views.xml',
        'views/visitor_company_views.xml',
        'views/visitor_vehicle_views.xml',
        'report/visitor_details_report.xml',
        'views/res_config_settings_views.xml',
        'views/visitor_register_form_portal.xml',
        'views/pre_approved_visitor_views.xml',
        'wizard/scan_qrcode_wizard_views.xml',
    ],
    'qweb': [
        "static/src/xml/tree_button.xml",
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
