{
    "name": "MetroGenie",
    "summary": "Gen AI-powered ERP quick actions & dashboard for Metro",
    "version": "14.0.0.1",
    "category": "Productivity",
    "author": "Metro Group Solutions",
    "website": "https://metrogroup.solutions/",
    "depends": ["base", "web", "account", "sale", "purchase", "stock", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "security/dashboard_security.xml",
        "data/import_sample_file_data.xml",
        "views/template.xml",
        "views/metro_genie_dashboard.xml",
        "views/metro_genie_suggestion_views.xml",
        "views/metro_genie_menu.xml",
        "data/metro_genie_suggestion_data.xml",
        "views/ir_attachment.xml",
        "wizard/import_file_wizard.xml",
    ],
    "qweb": [],
    # "assets": {},
    "images": ["static/description/icon.png"],
    "installable": True,
    "application": True,
    "auto_install": False,
}
