# -*- coding: utf-8 -*-
{
    'name': "MetroERP Customizations",
    'version': '1.2.1',
    'author': 'Metro Group',
    'category': 'All',
    'summary': 'MetroERP Customizations',
    'description': "",
    'website': 'https://metrogroup.solutions/',
    'depends': [
        'base',
        'mail',
        'fetchmail',
        'snailmail',
        # 'sms',
        'iap',
        'web_tour',
        'resource',
        'auth_signup',
        'web',
        'mail',
        'portal',
        'mail_bot',
        'account',
        'digest',
        'l10n_sg',
        'purchase',
        'base_import',
        'digest',
        'purchase_stock',
        'sale',
        'contacts',
        'stock',
        'base_setup',
        'sales_team',
        'analytic',
        'product',
        'sale_stock',
        #'coupon',
        'delivery',
        'om_account_followup',
        'product_expiry',
        'stock_picking_batch',
        'stock_landed_costs',
        'point_of_sale',
        'payment',
        #'base_vat',
        'sale_margin',
        ],
    'data': [
        'security/res_groups.xml',
        'views/menu.xml',
        'views/res_users.xml',
        'views/res_config_settings.xml',
        'views/web_client_template.xml',
        'views/portal_templates.xml',
        'views/email_templates.xml',
        'views/templates.xml',
        'views/digest_view.xml',
        'views/digest_template.xml',
        'views/ir_model.xml',
        'views/ir_ui_view.xml',
        'views/ir_actions_server.xml',
        'views/ir_default.xml',
        'views/account_move.xml',
        'views/analytic_account_views.xml',
        'views/account_cash_rounding_view.xml',
        'views/inherited_product.xml',
        'views/res_partner.xml',
        'views/res_partner_category.xml',
        'views/res_company.xml',
        'views/sale_order.xml',
        'views/stock_picking.xml',
        'views/invoice_portal_template.xml',
        'data/data.xml',
        'data/paper_format.xml',
        'data/mail_template.xml',
        'report/invoice_report_inherit.xml',
        'report/sale_report_inherit.xml',
        'report/purchase_report_inherit.xml',
        'report/delivery_report_inherit.xml',
        'report/airway_bill.xml',
        'security/ir_rule.xml',
        'security/ir.model.access.csv',
        'views/product_category_view.xml',
        'views/sale_portal_template.xml',
        'views/purchase_portal_template.xml',
        'views/product_attribute.xml',
        'views/product_template.xml',
        'views/ir_filter_views.xml',
        'views/mail_activity_view.xml',
        'views/sales_team.xml',
        'views/company_creation_logs.xml',
        'views/bank_accounts_views.xml',
        'views/delivery_carrier.xml',
        'views/mail_message_wizard.xml',
        'views/res_currency_views.xml',
        'views/account_journal.xml',
        'views/account_payment.xml',
        'views/account_payment_register.xml',
        'views/analytic_default_rules_views.xml',
        'views/product_packaging.xml',
        'views/stock_picking_batch_views.xml',
        'views/stock_landed_cost_views.xml',
        'views/delivery_portal_templates.xml',
        'views/stock_immediate_transfer_views.xml',
        'views/payment_token.xml',
        'views/account_bank_statement_views.xml',
        'views/product_tags_view.xml',
        'views/mail_template_views.xml',
        'wizard/sale_price_history_wizard.xml',
        'wizard/purchase_price_history_wizard.xml',
        'wizard/portal_wizard_views.xml',
        'wizard/sale_payment_link_views.xml',
        'wizard/payment_link_wizard_views.xml',
        'wizard/mail_message_wizard.xml',
        'views/account_tax_template.xml',
        'views/res_currency_log_views.xml',
    ],
    "qweb": [
        'static/src/xml/base.xml',
        'static/src/xml/client_action.xml',
        'static/src/xml/dashboard.xml',
        'static/src/xml/res_config_invite_users.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'pre_init_hook':'install_metrogroup_customizations',
}
