# -*- coding: utf-8 -*-

from . import res_users
#from . import res_groups
from . import ir_mail_server
from . import res_partner
from . import ir_ui_menu
from . import res_company
from . import res_config_settings
from . import mail_channel
from . import digest
from . import ir_model_access
from . import account_move
from . import analytic_account
from . import ir_module
from . import payment_acquirer
from . import digest_tip
from . import mail_message
from . import ir_actions_act_window
from . import sale
from . import purchase
from . import product
from . import base_models
from . import sr_purchase_price_history
from . import sr_sale_price_history
from . import stock_picking
from . import chart_template
from . import mail_followers
from . import product_category
from . import product_attribute
from . import mail_activity
from . import ir_filters
from . import company_creation_logs
from . import account_payment_term
from . import sale_order_template
from . import delivery
from . import account_analytic_default
from . import product_packaging
from . import stock_warehouse
from . import stock_rule
from . import account_journal
from . import product_tags
from . import account_payment
from . import base_partner_merge
from . import mail_render_mixin
from . import mail_thread
from . import account_tax_template
from . import mail_template
from . import res_currency_log
from . import res_currency
from . import account_account
