# -*- coding: utf-8 -*-

from odoo import fields, models, api, _
from odoo.exceptions import ValidationError
from datetime import datetime, timedelta
import pytz
import calendar


class InvoiceDetails(models.Model):
    _name = 'invoice.details'
    _description = 'Invoice Details'

    invoice_id = fields.Many2one('account.move', string="Invoice Status")
    date = fields.Date("Invoice Date")
    recurring_id = fields.Many2one('recurring.invoices')
    total_amount = fields.Float("Invoice Amount")
    company_id = fields.Many2one("res.company", related="invoice_id.company_id", string="Company")


class RecurringInvoice(models.Model):
    _name = 'recurring.invoices'
    _description = "Recurring Invoice"

    name = fields.Char('Name')
    partner_id = fields.Many2one('res.partner',string='Partner')
    first_date = fields.Datetime('Start Date')
    recurring_interval = fields.Integer('Recurring Interval',default=1)
    interval_type = fields.Selection([('days', 'Days'),
                                     ('weeks', 'Weeks'),
                                     ('months', 'Months')], default='days')
    recurring_number = fields.Integer('Recurring Number of Calls',default=1)
    state = fields.Selection([
        ('new', 'New'),
        ('running', 'In Progress'),
        ('done','Done'),
        ('Cancelled', 'Cancelled'),
    ], string='State',copy=False ,default="new")
    active = fields.Boolean(string='Active',default="True")
    reviewer_ids = fields.Many2one('res.users', "Observer", default=lambda self: self.env.user, required=True,
                                   readonly=True)
    scheduled_idss = fields.One2many('scheduled.invoices','recurring_invoice_id')
    user_id = fields.Many2one('res.users', string='User', default=lambda self: self.env.user)
    total = fields.Float('Amount Total')
    due_date = fields.Date('Due Date')
    cron_id = fields.Many2one('ir.cron', 'Cron Ref', help="Scheduler which runs on recurring invoice")
    inv_details_ids = fields.One2many('invoice.details','recurring_id', string="Invoice Details", help="show auto generated invoice details.")
    invoice_id = fields.Many2one('account.move','Account Invoice')
    company_id = fields.Many2one("res.company", related="invoice_id.company_id", string="Company")
    recurring_invoice_line_ids = fields.One2many('recurring.invoices.line', 'recurring_invoice_id', string='Invoice Lines')

    def cancel_button(self):
        self.state = 'Cancelled'
                
class ScheduleInvoice(models.Model):
    _name = 'scheduled.invoices'
    _description = "Schedule Invoice"

    recurring_invoice_id = fields.Many2one('recurring.invoices')
    schedule_date = fields.Date('Schedule Date')
    invoice = fields.Char('Invoice')
    company_id = fields.Many2one("res.company", related="recurring_invoice_id.company_id", string="Company")
    invoice_id = fields.Many2one('account.move','Account Invoice')

    def _cron_recurring_invoice_detail_create(self):
        today = fields.Date.today()
        effective_date = datetime.now(pytz.timezone(self._context.get('tz') or 'UTC'))
        scheduled_invoices = self.search([('schedule_date', '=', today)])
        for rec in scheduled_invoices:
            company = rec.company_id
            res = self._get_interpolation_dict(effective_date, company)
            rec = rec.sudo()
            if rec.schedule_date == today:
                invoice_details = self.env['invoice.details'].search([
                    ('recurring_id', '=', rec.recurring_invoice_id.id),('date', '=', today)
                    ])
                if not invoice_details and rec.invoice_id:
                    default = {'state': 'draft',
                               'invoice_user_id': rec.invoice_id.invoice_user_id.id,
                               'ref': rec.invoice_id.ref,
                               }
                    account_invoice_id = rec.invoice_id
                    new_invoice = account_invoice_id.sudo().copy(default=default)
                    new_invoice.message_post(
                        body="This record was automatically generated by the Recurring Invoice Scheduled Cron Job.")

                    new_invoice_line = new_invoice.invoice_line_ids
                    recurring_invoice_line = rec.recurring_invoice_id.recurring_invoice_line_ids
                    if len(new_invoice_line) == len(recurring_invoice_line):
                        for new_line, recurring_line in zip(new_invoice_line, recurring_invoice_line):
                            try:
                                interpolated_value = (recurring_line.name % res)
                            except Exception as e:
                                interpolated_value = recurring_line.name
                            new_line.name = interpolated_value
                    self.env['invoice.details'].create({
                        'invoice_id': new_invoice.id,
                        'date': today,
                        'recurring_id': rec.recurring_invoice_id.id,
                        'total_amount': new_invoice.amount_total
                    })
                    rec.recurring_invoice_id.state = 'running'
            if len(rec.recurring_invoice_id.scheduled_idss) == len(rec.recurring_invoice_id.inv_details_ids):
                rec.recurring_invoice_id.state = 'done'

    def _get_interpolation_dict(self, effective_date, company):
        res = {}
        interpolation = {
            'year': '%Y', 'month': '%m', 'day': '%d', 'y': '%y', 'doy': '%j', 'woy': '%W',
            'weekday': '%w', 'h24': '%H', 'h12': '%I', 'min': '%M', 'sec': '%S', 'month_name': '%B',
            'month_short': '%b',
        }
        for key, format in interpolation.items():
            res[key] = effective_date.strftime(format)
        month = effective_date.month
        quarter = (month - 1) // 3 + 1
        res['quarter'] = 'Q%d' % (quarter)
        res['quarter_start_month'] = calendar.month_abbr[3 * (quarter - 1) + 1]
        res['quarter_end_month'] = calendar.month_abbr[3 * (quarter - 1) + 3]
        # Fiscal year base calculation
        fiscal_year = self.env['account.fiscal.year'].sudo().search([
            ('date_from', '<=', effective_date.date()),
            ('date_to', '>=', effective_date.date()),
            ('company_id', '=', company.id),
        ], limit=1)
        if fiscal_year:
            fiscal_start = fiscal_year.date_from
            month_diff = (effective_date.month - fiscal_start.month) % 12
            fiscal_quarter = (month_diff // 3) + 1
            res['fiscal_quarter'] = f'Q{fiscal_quarter}'
            quarter_start_month_index = (fiscal_start.month + (fiscal_quarter - 1) * 3 - 1) % 12 + 1
            quarter_end_month_index = (quarter_start_month_index + 2 - 1) % 12 + 1
            # Month names
            res['fq_start_month'] = calendar.month_abbr[quarter_start_month_index]
            res['fq_end_month'] = calendar.month_abbr[quarter_end_month_index]
            fiscal_quarter_start_year = fiscal_start.year
            fiscal_quarter_end_year = fiscal_start.year
            if quarter_end_month_index < quarter_start_month_index:
                fiscal_quarter_end_year += 1
            res['fq_start_year'] = str(fiscal_quarter_start_year)
            res['fq_end_year'] = str(fiscal_quarter_end_year)
            res['fq_start_y'] = str(fiscal_quarter_start_year)[-2:]
            res['fq_end_y'] = str(fiscal_quarter_end_year)[-2:]
        return res


class RecurringInvoicesLine(models.Model):
    _name = 'recurring.invoices.line'
    _description = "Recurring Invoice Line"

    name = fields.Char(string='Label', tracking=True)
    product_id = fields.Many2one('product.product', string='Product', ondelete='restrict')
    account_id = fields.Many2one('account.account', string='Account')
    quantity = fields.Float(string='Quantity',
                            digits='Product Unit of Measure',
                            help="The optional quantity expressed by this line, eg: number of product sold. "
                                 "The quantity is not a legal requirement but is very useful for some reports.")
    price_unit = fields.Float(string='Unit Price', digits='Product Price')
    discount = fields.Float(string='Discount (%)', digits='Discount', default=0.0)
    product_uom_id = fields.Many2one('uom.uom', string='Unit of Measure')
    tax_ids = fields.Many2many(
        comodel_name='account.tax',
        string="Taxes",
        help="Taxes that apply on the base amount")
    currency_id = fields.Many2one('res.currency', string='Currency')
    price_subtotal = fields.Monetary(string='Subtotal', store=True, readonly=True,
                                     currency_field='currency_id')
    price_total = fields.Monetary(string='Total', store=True, readonly=True,
                                  currency_field='currency_id')
    recurring_invoice_id = fields.Many2one('recurring.invoices', string='Recurring Invoice')


