# -*- coding: utf-8 -*-
{
    'name': "MetroERP Progressive Billing",
    'version': '1.2.1',
    'author': 'Metro Group',
    'category': 'All',
    'summary': 'MetroERP Progressive Billing',
    'description': "",
    'website': 'https://metrogroup.solutions/',
    'depends': [
                'base',
                'sale',
                'sale_management',
                'metroerp_discount',
                'portal',
                'account_debit_note',
                'metroerp_customizations'
                ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'security/ir_rule.xml',
        'data/mail_data.xml',
        'data/sale_data.xml',
        'data/ir_sequence_data.xml',
        'data/progressive_billing_data.xml',
        'views/progressive_billing_qt_views.xml',
        'views/progressive_billing_qt_views.xml',
        'views/account_move_line.xml',
        'views/sale_portal_templates.xml',
        'wizard/progressive_billing_cancel_views.xml',
        'wizard/account_move_reversal_view.xml',
        'views/account_move.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
