# -*- coding: utf-8 -*-
from . import res_company
from . import res_config_settings
from . import res_partner
from . import account_move
from . import peppol_queue_out
from . import peppol_access_point
from . import peppol_queue_in
from . import purchase_order
from . import incoming_failed_logs
from . import invoice_responses_queue_out
from . import order_queue_out
from . import order_queue_in
from . import account_journal_inherit
from . import sale_order
from . import invoice_responses_queue_in
from . import c5_activation
from . import peppol_queue_c5_in
from . import peppol_queue_c5_out
from . import b2c_outgoing_invoices
from . import pcp_outgoing_invoices
from . import account_payment
from . import order_responses_queue_in
from . import order_responses_queue_out
from . import uom_code
from . import uom_uom
from . import ir_ui_menu
from . import order_cancel_queue_out
from . import order_change_queue_out
from . import order_balance_queue_out
from . import order_cancel_in
from . import order_change_in
from . import order_balance_in
from . import order_cancel_advance_responses_queue_out
from . import order_cancel_responses_queue_in
from . import order_change_responses_queue_out
from . import order_balance_responses_queue_out
from . import order_change_responses_queue_in
from . import order_balance_responses_queue_in
from . import ministries_statuary_boards
