# -*- coding: utf-8 -*-
from odoo import models,fields,_,api
from odoo.exceptions import ValidationError
from lxml import etree
import logging
import traceback
import requests
from datetime import datetime, date
import json

logger = logging.getLogger(__name__)


SELECTION_PEPPOL_QUEUE_OUT_STATE = [
    ('ready_to_send', 'Ready to Send'),
    ('Pending', 'Pending'),
    ('Processing', 'Processing'),
    ('Send Success', 'Send Success'),
    ('Send Error', 'Send Error'),
    ('Receive Success', 'Receive Success'),
    ('Completed', 'Completed'),
    ('error', 'Failed'),
    ('cancelled', 'Cancelled'),
]

ERROR_RESPONSES_DIC = {
    400: 'Bad Request',
    401: 'Unauthorized',
    404: 'Not Found',
    403: 'Forbidden',
    405: 'Method not allowed'
}

class InvoiceResponsesQueueOut(models.Model):
    _name = "invoice.responses.queue.out"
    _description = "Outgoing Invoices/Credit Notes Responses Queue" 
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'create_date desc'

    name = fields.Char(string="Name", store=True)
    inv_no = fields.Char('Invoice No')
    inv_issue_date= fields.Date('Invoice Issue Date')
    doc_type_code = fields.Char('Document Type Code')
    doc_type = fields.Selection([('invoices', 'Invoice'),('credit-notes', 'Credit Note')], string='Document Type')
    move_id = fields.Many2one("account.move", string="Invoice", readonly=True)
    partner_id = fields.Many2one('res.partner', related='move_id.partner_id', string='Customer', store=True)
    client_ref = fields.Char('Client Ref',
                             help="Unique client reference for this upload. Generated by ERP and used in further API Requests.", readonly=True)
    company_id = fields.Many2one('res.company', string="Company", store=True)
    state = fields.Selection(SELECTION_PEPPOL_QUEUE_OUT_STATE, string="Status", default='ready_to_send', readonly=True,
                             tracking=1, index=True)

    issue_date = fields.Datetime(string="Issued On")
    note = fields.Text(string="Note")
    response_code = fields.Selection([('AB', 'Message acknowledgement'), ('AP', 'Accepted'),('RE', 'Rejected'), ('IP', 'In process'),('UQ', 'Under query'),
                                    ('CA', 'Conditionally accepted'),('PD', 'Paid')], string="Response Code", required=True)
    effective_date = fields.Date('Effective Date', default=fields.Datetime.now(), required=True)

    source_doc_id = fields.Many2one("peppol.queue.in", string="Source Document", readonly=True)

    sender_party_id = fields.Char('Sender ID', readonly=True)
    sender_party_name = fields.Char('Sender Party Name', readonly=True)
    sender_party_contact_name = fields.Char('Contact Name')
    sender_party_contact_telephone = fields.Char('Contact Telephone')
    sender_party_contact_email = fields.Char('Contact Email')

    receiver_party_id = fields.Char('Receiver ID', readonly=True)
    receiver_party_name = fields.Char('Receiver Party Name', readonly=True)

    upload_time = fields.Char('Document uploaded/received time')
    
    extracted_senderid = fields.Char('Sender ID', help="Sender id extracted from the uploaded xml", tracking=1)
    extracted_receiverid = fields.Char('Receiver ID', help="Receiver id extracted from the uploaded xml", tracking=1)
    extracted_docno = fields.Char('Document No', help="Document number extracted from the uploaded xml", tracking=1)
    instance_id = fields.Char('Instance ID',
        help="Generated unique id for the document when sending to the peppol network.")
    server_receipt = fields.Char("Server Receipt",
        help="Unique server receipt number generated for the document(s) upload. This is received from the DataPost API extracted from the JSON response.")
    invalidated = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Invalidated Document",
        help="true denotes an Invalidated document. Documents become invalidated when a new document with the same Document number received again.",
        tracking=1)     
    status_message = fields.Text('Status Message', default=False, tracking=1, help="Detailed description for the status.")
    xml_data = fields.Text("Sent XML Data", 
        help="For Technical Use only")

    docstatusapi_json_response = fields.Text('Document Status API Response', 
        help="We track the response and store in this record for the sake of reference.")   
    sent = fields.Boolean(string="Sent", readonly=True)
    sentapi_json_response = fields.Text('Send Documents API Response',
        help="We track the response and store in this record for the sake of reference.")

    status_ids = fields.One2many('invoice.response.status', 'inv_response_out_id', string="Status")

    
    @api.depends('move_id')
    def _compute_company(self):
        for entry in self:
            document = entry.move_id
            try:
                company = document and document.company_id or None
            except AttributeError:  # Document doesn't have company_id
                company = None
            entry.company_id = company

            
    @api.model
    def create(self, vals):
        vals['name'] = self.env['ir.sequence'].next_by_code('invoice.responses.queue.out')
        obj =  super(InvoiceResponsesQueueOut, self).create(vals)
        print("obj.source_doc_id ==",obj.source_doc_id)
        if obj.source_doc_id:
            obj.source_doc_id.write({'invoice_response_out_ids': [(4, obj.id)]})
        return obj

    # @api.depends('move_id')
    # def _compute_name(self):
    #     for entry in self:
    #         entry.name = "%s" % entry.move_id.name

    def generate_application_response_xml(self):
        print("generate_application_response_xml ===",self)
        self.issue_date = datetime.now()
        print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Method called",self.issue_date)
        
        nsmap = {
            None: "urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2",
            'cbc': "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
            'cac': "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
            'xsi': "http://www.w3.org/2001/XMLSchema-instance"
          }

        root = etree.Element(
            "{urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2}ApplicationResponse",
            nsmap=nsmap
        )

        ns = {
            "cac": "{urn:oasis:names:specification:ubl:schema:xsd:"
                   "CommonAggregateComponents-2}",
            "cbc": "{urn:oasis:names:specification:ubl:schema:xsd:"
                   "CommonBasicComponents-2}"
       }

        customization_id = etree.Element(ns['cbc'] + "CustomizationID")
        customization_id.text = "urn:fdc:peppol.eu:poacc:trns:invoice_response:3"
        profile_id = etree.Element(ns['cbc'] + "ProfileID")
        profile_id.text = "urn:fdc:peppol.eu:poacc:bis:invoice_response:3"

        document_id = etree.Element(ns['cbc'] + "ID")
        document_id.text = self.name

        issue_date = etree.Element(ns['cbc'] + "IssueDate")
        issue_date.text = str(self.issue_date.date())
        issue_time = etree.Element(ns['cbc'] + "IssueTime")
        issue_time.text = self.issue_date.strftime('%H:%M:%S')

        # Create SenderParty element and its child elements        
        sender_party_id = self.sender_party_id.split(":")[1]
        scheme_id = self.sender_party_id.split(":")[0]

        sender_party = etree.Element(ns['cac'] + "SenderParty")

        endpoint_id = etree.Element(ns['cbc'] + "EndpointID", schemeID=scheme_id)
        endpoint_id.text = self.sender_party_id.split(":")[1]

        party_legal_entity = etree.Element(ns['cac'] + "PartyLegalEntity")
        registration_name = etree.Element(ns['cbc'] + "RegistrationName")
        
        partner_obj = self.env['res.partner'].search(['|',('peppol_identifier','=',sender_party_id), ('peppol_identifier','ilike',sender_party_id)], limit=1)
        if not partner_obj:
            raise ValidationError('Sender Partner in ERP is not found with Peppol Identifier: ' + self.sender_party_id)
        else:
            registration_name.text = partner_obj.name

        if self.sender_party_contact_name:
            contact = etree.Element(ns['cac'] + "Contact")

            name = etree.Element(ns['cbc'] + "Name")
            name.text = self.sender_party_contact_name or ""
            telephone = etree.Element(ns['cbc'] + "Telephone")
            telephone.text = self.sender_party_contact_telephone or ""
            electronic_mail = etree.Element(ns['cbc'] + "ElectronicMail")
            electronic_mail.text = self.sender_party_contact_email or ""

            contact.append(name)
            contact.append(telephone)
            contact.append(electronic_mail)

            

        party_legal_entity.append(registration_name)

        sender_party.append(endpoint_id)
        sender_party.append(party_legal_entity)
        if self.sender_party_contact_name:
            sender_party.append(contact)
        

        # Create ReceiverParty element and its child elements
        receiver_peppol_id = self.receiver_party_id.split(":")[1]
        scheme_id = self.receiver_party_id.split(":")[0]

        receiver_party = etree.Element(ns['cac'] + "ReceiverParty")        

        endpoint_id_receiver = etree.Element(ns['cbc'] + "EndpointID", schemeID=scheme_id)
        endpoint_id_receiver.text = receiver_peppol_id

        party_legal_entity_receiver = etree.Element(ns['cac'] + "PartyLegalEntity")
        registration_name_receiver = etree.Element(ns['cbc'] + "RegistrationName")

        partner_obj = self.env['res.partner'].search(['|',('peppol_identifier','=',receiver_peppol_id), ('peppol_identifier','ilike',receiver_peppol_id)], limit=1)
        if not partner_obj:
            raise ValidationError('Receiver Partner in ERP is not found with Peppol Identifier: ' + self.receiver_party_id)
        else:
            registration_name_receiver.text = partner_obj.name

        party_legal_entity_receiver.append(registration_name_receiver)

        receiver_party.append(endpoint_id_receiver)
        receiver_party.append(party_legal_entity_receiver)

        # ----- Document response
        document_response = etree.Element(ns['cac'] + "DocumentResponse")

        response = etree.Element(ns['cac'] + "Response")

        response_code = etree.Element(ns['cbc'] + "ResponseCode", listID="UNCL4343OpSubset")
        response_code.text = self.response_code

        effective_date = etree.Element(ns['cbc'] + "EffectiveDate")
        effective_date.text = str(self.effective_date)

        response.append(response_code)
        response.append(effective_date)

        for status_line in self.status_ids:
            status = etree.Element(ns['cac'] + "Status")

            if status_line.clarification_code_id:
                status_reason_code = etree.Element(ns['cbc'] + "StatusReasonCode", listID=status_line.clarification_code_id.status_type)
                status_reason_code.text = status_line.clarification_code_id.code

                status.append(status_reason_code)

            if status_line.clarification_description:
                status_reason = etree.Element(ns['cbc'] + "StatusReason")
                status_reason.text = status_line.clarification_description

                status.append(status_reason)        
            
            if status_line.condition_code_ids:
                for condition_line in status_line.condition_code_ids:
                    condition = etree.Element(ns['cac'] + "Condition")

                    if condition_line.condition_code:
                        condition_code = etree.Element(ns['cbc'] + "AttributeID")
                        condition_code.text = condition_line.condition_code

                        condition.append(condition_code)

                    if condition_line.condition_value:
                        condition_value = etree.Element(ns['cbc'] + "Description")
                        condition_value.text = condition_line.condition_value

                        condition.append(condition_value)

                    status.append(condition)

        if self.status_ids:
            response.append(status)

        document_response.append(response)

        #----- <cac:DocumentResponse>
        document_reference = etree.Element(ns['cac'] + "DocumentReference")

        document_id_ref = etree.Element(ns['cbc'] + "ID")
        document_id_ref.text = self.source_doc_id.invoice_no

        issue_date_ref = etree.Element(ns['cbc'] + "IssueDate")
        issue_date_ref.text = str(self.inv_issue_date)

        document_type_code = etree.Element(ns['cbc'] + "DocumentTypeCode")
        document_type_code.text = self.doc_type_code

        document_reference.append(document_id_ref) # <cac:DocumentResponse> -> <cac:DocumentReference> -> <cbc:ID>
        document_reference.append(issue_date_ref) # <cac:DocumentResponse> -> <cac:DocumentReference> -> <cbc:IssueDate>
        document_reference.append(document_type_code) # <cac:DocumentResponse> -> <cac:DocumentReference> -> <cbc:DocumentTypeCode>

        document_response.append(document_reference) # <cac:DocumentResponse>

        # Append all elements to the root
        root.append(customization_id)
        root.append(profile_id)
        root.append(document_id)
        root.append(issue_date)
        root.append(issue_time)
        if self.note:
            note = etree.Element(ns['cbc'] + "Note")        
            note.text = str(self.note)
            root.append(note)
        root.append(sender_party)
        root.append(receiver_party)
        root.append(document_response)
        
        xml_tree = etree.ElementTree(root)

        xml_string = etree.tostring(
            xml_tree, pretty_print=True, encoding="utf-8", xml_declaration=True
        )
        print("xml_string ===",xml_string)
        print("xml_string.decode('utf-8') == ",xml_string.decode('utf-8'))

        # with open("application_response.xml", "wb") as xml_file:
        #     xml_file.write(xml_string)

        return xml_string
        
    def _send(self):
        print("_send ===")
        for obj in self:
            obj.check_clarification_required()            
            xml_string = ''
            access_point = self.env['peppol.access.point.sg'].sudo().search([('company_id','=',obj.company_id.id)], order="create_date")
            if not access_point:
                obj.write({'state': 'error'})
                log = _("Access Point configuration is not defined.")
                obj.message_post(body=log)
                continue
            try:
                xml_string = obj.generate_application_response_xml()
                base_url = access_point.endpoint
                api_version = access_point.api_version
                base64_string = access_point.get_basic_auth_token()
                client_ref = access_point.get_client_ref()
                timeout = self.env['ir.config_parameter'].sudo().get_param('api_timeout', default='20')
                # headers = {
                #     "Accept": "*/*",
                #     "Authorization": "Basic {}".format(base64_string),
                # }
                headers = {
                    "Accept": "*/*",
                    "Authorization": f"Bearer {access_point.access_token}",
                }
                files = {
                    'document': (obj.inv_no + '.xml', xml_string.decode('utf-8'), 'application/xml')
                }
                try:
                    response = requests.post(
                        '%s/api/business/%s/invoice-responses/peppol-invoice-response-2/%s' % (base_url, api_version, client_ref),
                        files=files,
                        headers=headers,
                        timeout=int(timeout))
                except requests.exceptions.Timeout:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _(
                        '<b>An Exception has arised.</b><br/>A timeout occured while trying to perform the Send '
                        'Documents API.')
                    obj.message_post(body=log)
                    continue
                except requests.exceptions.HTTPError:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _(
                        '<b>An Exception has arised.</b><br/>HTTP error occurred while trying to perform the Send '
                        'Documents API.')
                    obj.message_post(body=log)
                    continue
                except Exception as e:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _(
                        '<b>An Exception has arised.</b><br/>The Send Documents API is not reachable, please try '
                        'again later.<br/> '
                        'Exception handler details: %s') % (
                              repr(e))
                    obj.message_post(body=log)
                    continue
                status_code = response.status_code
                response_data = json.loads(response.text)
                print("type(response_data) ===",type(response_data))
                print("status_code ===",status_code)
                print("response_data ===",response_data)
                print("isinstance(response_data, dict) ===",isinstance(response_data, dict))
                if status_code == 200 and isinstance(response_data, dict):
                    obj.write({'state': response_data['info'][0].get('status'),
                               'client_ref': client_ref,
                               'server_receipt': response_data.get('serverReceipt'),
                               'status_message': response_data['info'][0].get('statusMessage'),
                               'upload_time': response_data['info'][0].get('uploadTime'),
                               'extracted_senderid': response_data['info'][0].get('sender'),
                               'extracted_receiverid': response_data['info'][0].get('receiver'),
                               'extracted_docno': response_data['info'][0].get('documentNo'),
                               'invalidated': 'yes' if response_data['info'][0].get('invalidated') == True else 'no',
                               'sentapi_json_response': response_data,
                               'sent': True,
                               'xml_data': xml_string})
                else:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _("<b>Send Documents API responded as {} {}</b><br/>{}".format(status_code,
                                                                                         ERROR_RESPONSES_DIC.get(
                                                                                             status_code, ''),
                                                                                         response_data))
                    obj.message_post(body=log)
            except Exception as e:
                obj.write({'state': 'error', 'xml_data': xml_string})
                log = _('<b>A Critical Error has arised.</b><br/>Traceback::%s<br/><br/>%s') % (traceback.format_exc(), repr(e))
                obj.message_post(body=log)
                
                
    def action_send(self):
        print("action_send ===",self)
        if self.filtered(lambda q: q.state != 'ready_to_send'):
            raise ValidationError(_("Please select only 'Ready to Send' queue entries to perform this action."))
        self._send()

    def action_check_status(self):
        if self.filtered(lambda q: q.state not in 'Pending,Processing,Send Success'.split(',')):
            raise ValidationError(
                _("Please select only either of the following states queue entries for this action to perform.\n "
                  "'Pending, Processing and Send Success'. "))
        self._check_status()
        
    def action_retry(self):
        if self.filtered(lambda q: q.state not in 'error,Send Error'.split(',')):
            raise ValidationError(
                _("Please select only 'Error', 'Send Error' & 'Cancelled' queue entries to perform this action."))
        # check_status_api = self.filtered(lambda q: q.sent and q.state in ['error'])
        # check_status_api._check_status()

        resend_doc_api = self.filtered(lambda q: q.state in ('Send Error', 'error'))
        resend_doc_api._send()

    def action_reset(self):
        if self.filtered(lambda q: q.state not in 'error,cancelled'.split(',')):
            raise ValidationError(_("Please select only 'Error' or 'Cancelled' queue entries to perform this action."))
        self.write({'state': 'ready_to_send'})
        
    def action_cancel(self):
        if self.filtered(lambda q: q.state not in ('ready_to_send', 'error', 'Send Error')):
            raise ValidationError(
                _("Please select only 'Ready to Send' or 'Error' queue entries to perform this action."))
        self.write({'state': 'cancelled'})
        
    def _check_status(self):
        print("\n_check_status() >>>>")
        for obj in self:
            access_point = self.env['peppol.access.point.sg'].sudo().search([('company_id','=',obj.company_id.id)], order="create_date")
            if not access_point:
                obj.write({'state': 'error'})
                log = _("Access Point configuration is not defined.")
                obj.message_post(body=log)
                continue
            base_url = access_point.endpoint
            api_version = access_point.api_version
            base64_string = access_point.get_basic_auth_token()  # TODO: Dont calculate but instead calculate and store as one time.
            timeout = self.env['ir.config_parameter'].sudo().get_param('api_timeout', default='20')
            # headers = {
            #     "Accept": "*/*",
            #     "Authorization": "Basic {}".format(base64_string),
            # }
            headers = {
                "Accept": "*/*",
                "Authorization": f"Bearer {access_point.access_token}",
            }
            print('%s/business/%s/invoice-responses.json?type=1&sender=%s&receiver=%s&invoiceNo=%s' % (base_url, api_version, obj.sender_party_id, obj.receiver_party_id, obj.inv_no),)
            
            try:
                response = requests.get(
                    '%s/api/business/%s/invoice-responses/peppol-invoice-response-2/%s' % (base_url, api_version, obj.client_ref),
                    headers=headers,
                    timeout=int(timeout))
            except requests.exceptions.Timeout:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>A timeout occured while trying to perform the Check Sent '
                    'Document status Api.')
                obj.message_post(body=log)
                continue
            except requests.exceptions.HTTPError:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>HTTP error occurred while trying to perform the Check Sent '
                    'Document status Api.')
                obj.message_post(body=log)
                continue
            except Exception as e:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>The Check Document status Api is not reachable, '
                    'please try again later.<br/>Exception handler details: %s') % (repr(e))
                obj.message_post(body=log)
                continue
            status_code = response.status_code
            response_data = json.loads(response.text)
            print("\nstatus_code ===",status_code)
            print("response_data ===",response_data)
            if status_code == 200 and isinstance(response_data, dict):
                for dic in response_data['info']:
                    if dic.get('status') == 'Send Success':
                        state = dic['status'] if dic['status'] == 'Completed' else \
                            dic.get('status')
                        break
                    else:
                        state = dic.get('status')

                obj.write({
                    'state': state,
                    'status_message': dic.get('statusMessage'),
                    'invalidated': 'yes' if dic.get('invalidated') is True else 'no',
                    'extracted_senderid': dic.get('sender'),
                    'extracted_receiverid': dic.get('receiver'),
                    'extracted_docno': dic.get('documentNo'),
                    'instance_id': dic.get('instanceId'),
                    'docstatusapi_json_response': response_data})
                obj.message_post(body=_("Check Document status Api responded with: <br/>{}".format(response_data)))
            else:
                obj.write({'state': 'error'})
                log = _(
                    "Check Document status Api responded with status code: <b>{} {}</b><br/>{}".format(status_code,
                                                                                                            ERROR_RESPONSES_DIC.get(
                                                                                                                status_code,
                                                                                                                ''),
                                                                                       response_data))
                obj.message_post(body=log)
                
    def check_clarification_required(self):
        for obj in self:
            if obj.response_code in ['UQ','RE','CA'] and not obj.status_ids:
                raise ValidationError("Clarification is mandatory for the selected status. \nClarification may be given as a code, a description or both. If both are used, they must indicate the same clarification.\nPlease do the required updations.")
            
class InvoiceResponseStatus(models.Model):
    _name = "invoice.response.status"

    inv_response_out_id = fields.Many2one('invoice.responses.queue.out')
    inv_response_in_id = fields.Many2one('invoice.responses.queue.in')
    list_identifier = fields.Selection([('OPStatusAction','Actions'),('OPStatusReason','Reasons')], string='List Identifier')
    clarification_code_id = fields.Many2one("clarification.codes",string="Clarification Code")
    clarification_description = fields.Text('Clarification Description')
    condition_code_ids = fields.One2many('status.condition.codes', 'response_status_id', 'Condition Codes')

    @api.onchange('list_identifier')
    def onchange_list_identifier(self):
        self.clarification_code_id = False
        self.clarification_description = False

class StatusConditionCodes(models.Model):
    _name = "status.condition.codes"
    _rec_name = 'condition_code'

    condition_code = fields.Char('Condition Code')
    condition_value = fields.Char('Condition Value')
    response_status_id = fields.Many2one('invoice.response.status')

class ClarificationCodes(models.Model):
    _name = "clarification.codes"
    _description = "Clarification Codes"
    
    name = fields.Char(string="Name")
    status_type = fields.Selection([('OPStatusAction','Actions'),('OPStatusReason','Reasons')], string="Status Type")
    description = fields.Text(string="Description of the Code")
    code = fields.Char(string="Technical Code")

