# -*- coding: utf-8 -*-
from docutils.nodes import reference

from odoo import models, fields, _, api
from odoo.exceptions import ValidationError
from lxml import etree
import logging
import traceback
import requests
from datetime import datetime, date
import json

logger = logging.getLogger(__name__)

SELECTION_PEPPOL_QUEUE_OUT_STATE = [
    ('ready_to_send', 'Ready to Send'),
    ('Pending', 'Pending'),
    ('Processing', 'Processing'),
    ('Send Success', 'Send Success'),
    ('Send Error', 'Send Error'),
    ('Receive Success', 'Receive Success'),
    ('Completed', 'Completed'),
    ('error', 'Failed'),
    ('cancelled', 'Cancelled'),
]

ERROR_RESPONSES_DIC = {
    400: 'Bad Request',
    401: 'Unauthorized',
    404: 'Not Found',
    403: 'Forbidden',
    405: 'Method not allowed'
}


class OrderChangeResponsesQueueOut(models.Model):
    _name = "order.change.responses.queue.out"
    _description = "Outgoing Order Responses Queue"
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = "create_date desc, id desc"

    name = fields.Char(string="Name", compute="_compute_name", store=True)
    order_no = fields.Char('Order No')
    order_id = fields.Many2one("purchase.order", string="Purchase Order")
    source_doc_id = fields.Many2one("order.change.in", string="Source Document", readonly=True)

    partner_id = fields.Many2one('res.partner', related='order_id.partner_id', string='Vendor', store=True)
    client_ref = fields.Char('Client Ref',
                             help="Unique client reference for this upload. Generated by ERP and used in further API Requests.")
    state = fields.Selection(SELECTION_PEPPOL_QUEUE_OUT_STATE, string="Status", default='ready_to_send', readonly=True,
                             tracking=1, index=True)
    issue_date = fields.Datetime(string="Issue Datetime")
    effective_date = fields.Date('Effective Date', default=fields.Datetime.now(), required=True)

    company_id = fields.Many2one('res.company', string="Company", compute="_compute_company", store=True)
    sent = fields.Boolean(string="Sent", readonly=True)
    response_code = fields.Selection([
        ('AB', 'Message acknowledgement'),
        ('AP', 'Accepted'),
        ('RE', 'Rejected'),
        ('CA', 'Conditionally accepted'),
    ], string="Response", readonly=True)
    server_receipt = fields.Char("Server Receipt",
                                 help="Unique server receipt number generated for the document(s) upload. This is received from the DataPost API extracted from the JSON response.")
    status_message = fields.Text('Status Message', default=False, tracking=1,
                                 help="Detailed description for the status.")
    upload_time = fields.Char('Document uploaded/received time')
    extracted_senderid = fields.Char('Sender ID', help="Sender id extracted from the uploaded xml", tracking=1)
    extracted_receiverid = fields.Char('Receiver ID', help="Receiver id extracted from the uploaded xml", tracking=1)
    extracted_totamount = fields.Char('Total Amount', help="Document total amount extracted from the uploaded xml",
                                      tracking=1)
    extracted_docno = fields.Char('Document No', help="Document number extracted from the uploaded xml", tracking=1)
    sentapi_json_response = fields.Text('Send Documents API Response',
                                        help="We track the response and store in this record for the sake of reference.")
    invalidated = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Invalidated Document",
                                   help="true denotes an Invalidated document. Documents become invalidated when a new document with the same Document number received again.",
                                   tracking=1)
    instance_id = fields.Char('Instance ID',
                              help="Generated unique id for the document when sending to the peppol network.")
    docstatusapi_json_response = fields.Text('Document Status API Response',
                                             help="We track the response and store in this record for the sake of reference.")
    xml_data = fields.Text("XML Order Data", help="For Technical Use only")
    # attachment_ids = fields.Many2many('ir.attachment', 'order_queue_out_attach_rel', 'queue_response_id', 'attachment_id',
    #                                   string='Documents')
    sender_party_name = fields.Char('Sender Party Name', readonly=True)
    sender_party_contact_name = fields.Char('Contact Name')
    sender_party_contact_telephone = fields.Char('Contact Telephone')
    sender_party_contact_email = fields.Char('Contact Email')
    note = fields.Text(string="Note")
    receiver_party_name = fields.Char('Receiver Party Name', readonly=True)



    # @api.depends('order_id')
    # def _compute_company(self):
    #     for order in self:
    #         document = order.order_id
    #         try:
    #             company = document and document.company_id or None
    #         except AttributeError:  # Document doesn't have company_id
    #             company = None
    #         order.company_id = company

    @api.model
    def create(self, vals):
        vals['name'] = self.env['ir.sequence'].next_by_code('order.change.responses.queue.out')
        obj = super(OrderChangeResponsesQueueOut, self).create(vals)
        print("obj.source_doc_id ==", obj.source_doc_id)
        # if obj.source_doc_id:
        #     obj.source_doc_id.write({'order_response_out_ids': [(4, obj.id)]})
        return obj

    # @api.depends('move_id')
    # def _compute_name(self):
    #     for entry in self:
    #         entry.name = "%s" % entry.move_id.name

    def generate_application_response_xml(self):
        print("generate_application_response_xml ===", self)
        self.issue_date = datetime.now()

        nsmap = {
            None: "urn:oasis:names:specification:ubl:schema:xsd:OrderResponse-2",
            'cbc': "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
            'cac': "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
        }
        # root element of order reference
        root = etree.Element("OrderResponse", nsmap=nsmap)

        ns = {
            "cac": "{urn:oasis:names:specification:ubl:schema:xsd:"
                   "CommonAggregateComponents-2}",
            "cbc": "{urn:oasis:names:specification:ubl:schema:xsd:"
                   "CommonBasicComponents-2}"
        }

        customization_id = etree.SubElement(root, ns["cbc"] + "CustomizationID")
        customization_id.text = "urn:fdc:peppol.eu:poacc:trns:order_response_advanced:3"
        profile_id = etree.SubElement(root, ns["cbc"] + "ProfileID")
        profile_id.text = "urn:fdc:peppol.eu:poacc:bis:advanced_ordering:3"

        doc_id = etree.SubElement(root, ns["cbc"] + "ID")
        doc_id.text = self.name
        if self.source_doc_id.so_id:
            so_id = etree.SubElement(root, ns["cbc"] + "SalesOrderID")
            so_id.text = self.source_doc_id.so_id.name

        issue_date = etree.SubElement(root, ns["cbc"] + "IssueDate")
        issue_date.text = str(self.issue_date.date())
        issue_time = etree.SubElement(root, ns["cbc"] + "IssueTime")
        issue_time.text = str(self.issue_date.time())

        order_response_code = etree.SubElement(root, ns["cbc"] + "OrderResponseCode")

        order_response_code.text = self.response_code
        if self.note:
            note = etree.Element(ns['cbc'] + "Note")
            note.text = str(self.note)

        doc_currency = etree.SubElement(root, ns["cbc"] + "DocumentCurrencyCode")
        doc_currency.text = str(self.source_doc_id.document_currency_code)
        # orderReference
        order_ref = etree.SubElement(root, ns["cac"] + "OrderReference")
        order_id = etree.SubElement(order_ref, ns["cbc"] + "ID")
        order_id.text = self.order_no

        # sellersupplierparty(sender party)
        seller_party_id = self.extracted_senderid.split(":")[1]
        scheme_id = self.extracted_senderid.split(":")[0]
        seller = etree.SubElement(root, ns["cac"] + "SellerSupplierParty")
        seller_party = etree.SubElement(seller, ns["cac"] + "Party")

        seller_endpoint = etree.SubElement(seller_party, ns["cbc"] + "EndpointID", schemeID=scheme_id)
        seller_endpoint.text = seller_party_id

        partner_obj = self.env['res.partner'].search(['|',('peppol_identifier','=',seller_party_id), ('peppol_identifier','ilike',seller_party_id)], limit=1)
        # PartyIdentification
        if partner_obj:
            if partner_obj.l10n_sg_unique_entity_number:
                seller_identification = etree.SubElement(seller_party, ns["cac"] + "PartyIdentification")
                seller_identification_id = etree.SubElement(seller_identification, ns["cbc"] + "ID", schemeID=scheme_id)
                seller_identification_id.text = partner_obj.l10n_sg_unique_entity_number

        # PartyLegalEntity
        seller_legal_entity = etree.SubElement(seller_party, ns["cac"] + "PartyLegalEntity")
        registration_name = etree.SubElement(seller_legal_entity, ns["cbc"] + "RegistrationName")
        if not partner_obj:
            raise ValidationError('Sender Partner in ERP is not found with Peppol Identifier: ' + self.extracted_senderid)
        else:
            registration_name.text = partner_obj.name

        # BuyerCustomerParty
        receiver_party_id = self.extracted_receiverid.split(":")[1]
        scheme_id = self.extracted_receiverid.split(":")[0]
        buyer = etree.SubElement(root, ns["cac"] + "BuyerCustomerParty")
        buyer_party = etree.SubElement(buyer, ns["cac"] + "Party")

        buyer_endpoint = etree.SubElement(buyer_party, ns["cbc"] + "EndpointID", schemeID=scheme_id)
        buyer_endpoint.text = receiver_party_id

        partner_obj = self.env['res.partner'].search(
            ['|', ('peppol_identifier', '=', receiver_party_id), ('peppol_identifier', 'ilike', receiver_party_id)],
            limit=1)

        # PartyIdentification
        if partner_obj:
            if partner_obj.l10n_sg_unique_entity_number:
                buyer_identification = etree.SubElement(buyer_party, ns["cac"] + "PartyIdentification")
                buyer_identification_id = etree.SubElement(buyer_identification, ns["cbc"] + "ID", schemeID=scheme_id)
                buyer_identification_id.text = partner_obj.l10n_sg_unique_entity_number

        # PartyLegalEntity
        buyer_legal_entity = etree.SubElement(buyer_party, ns["cac"] + "PartyLegalEntity")
        registration_name_receiver = etree.SubElement(buyer_legal_entity, ns["cbc"] + "RegistrationName")
        if not partner_obj:
            raise ValidationError(
                'Receiver Partner in ERP is not found with Peppol Identifier: ' + self.extracted_receiverid)
        else:
            registration_name_receiver.text = partner_obj.name

        xml_string = etree.tostring(
            root, pretty_print=True, encoding="utf-8", xml_declaration=True
        )
        print("xml_string ===", xml_string)
        return xml_string

    def _send(self):
        print("_send ===")
        for obj in self:
            # obj.check_clarification_required()
            xml_string = ''
            access_point = self.env['peppol.access.point.sg'].sudo().search([('company_id', '=', obj.company_id.id)],
                                                                            order="create_date")
            if not access_point:
                obj.write({'state': 'error'})
                log = _("Access Point configuration is not defined.")
                obj.message_post(body=log)
                continue
            try:
                xml_string = obj.generate_application_response_xml()
                base_url = access_point.endpoint
                api_version = access_point.api_version
                base64_string = access_point.get_basic_auth_token()
                client_ref = access_point.get_client_ref()
                timeout = self.env['ir.config_parameter'].sudo().get_param('api_timeout', default='20')
                # headers = {
                #     "Accept": "*/*",
                #     "Authorization": "Basic {}".format(base64_string),
                # }
                headers = {
                    "Accept": "*/*",
                    "Authorization": f"Bearer {access_point.access_token}",
                }
                files = {
                    'document': (obj.name + '.xml', xml_string.decode('utf-8'), 'application/xml')
                }
                try:
                    response = requests.post(
                        '%s/api/business/%s/order-response-advanced/peppol-order-response-advanced/%s' % (
                        base_url, api_version, client_ref),
                        files=files,
                        headers=headers,
                        timeout=int(timeout))
                except requests.exceptions.Timeout:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _(
                        '<b>An Exception has arised.</b><br/>A timeout occured while trying to perform the Send '
                        'Documents API.')
                    obj.message_post(body=log)
                    continue
                except requests.exceptions.HTTPError:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _(
                        '<b>An Exception has arised.</b><br/>HTTP error occurred while trying to perform the Send '
                        'Documents API.')
                    obj.message_post(body=log)
                    continue
                except Exception as e:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _(
                        '<b>An Exception has arised.</b><br/>The Send Documents API is not reachable, please try '
                        'again later.<br/> '
                        'Exception handler details: %s') % (
                              repr(e))
                    obj.message_post(body=log)
                    continue
                status_code = response.status_code
                response_data = json.loads(response.text)
                print("type(response_data) ===", type(response_data))
                print("status_code ===", status_code)
                print("response_data ===", response_data)
                print("isinstance(response_data, dict) ===", isinstance(response_data, dict))
                if status_code == 200 and isinstance(response_data, dict):
                    obj.write({'state': response_data['info'][0].get('status'),
                               'client_ref': client_ref,
                               'server_receipt': response_data.get('serverReceipt'),
                               'status_message': response_data['info'][0].get('statusMessage'),
                               'upload_time': response_data['info'][0].get('uploadTime'),
                               'extracted_senderid': response_data['info'][0].get('sender'),
                               'extracted_receiverid': response_data['info'][0].get('receiver'),
                               'extracted_docno': response_data['info'][0].get('documentNo'),
                               'invalidated': 'yes' if response_data['info'][0].get('invalidated') == True else 'no',
                               'sentapi_json_response': response_data,
                               'sent': True,
                               'xml_data': xml_string})
                else:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _("<b>Send Documents API responded as {} {}</b><br/>{}".format(status_code,
                                                                                         ERROR_RESPONSES_DIC.get(
                                                                                             status_code, ''),
                                                                                         response_data))
                    obj.message_post(body=log)
            except Exception as e:
                obj.write({'state': 'error', 'xml_data': xml_string})
                log = _('<b>A Critical Error has arised.</b><br/>Traceback::%s<br/><br/>%s') % (
                traceback.format_exc(), repr(e))
                obj.message_post(body=log)

    def action_send(self):
        print("action_send ===", self)
        if self.filtered(lambda q: q.state != 'ready_to_send'):
            raise ValidationError(_("Please select only 'Ready to Send' queue entries to perform this action."))
        self._send()

    def action_check_status(self):
        if self.filtered(lambda q: q.state not in 'Pending,Processing,Send Success'.split(',')):
            raise ValidationError(
                _("Please select only either of the following states queue entries for this action to perform.\n "
                  "'Pending, Processing and Send Success'. "))
        self._check_status()

    def action_retry(self):
        if self.filtered(lambda q: q.state not in 'error,Send Error'.split(',')):
            raise ValidationError(
                _("Please select only 'Error', 'Send Error' & 'Cancelled' queue entries to perform this action."))
        # check_status_api = self.filtered(lambda q: q.sent and q.state in ['error'])
        # check_status_api._check_status()

        resend_doc_api = self.filtered(lambda q: q.state in ('Send Error', 'error'))
        resend_doc_api._send()

    def action_reset(self):
        if self.filtered(lambda q: q.state not in 'error,cancelled'.split(',')):
            raise ValidationError(_("Please select only 'Error' or 'Cancelled' queue entries to perform this action."))
        self.write({'state': 'ready_to_send'})

    def action_cancel(self):
        if self.filtered(lambda q: q.state not in ('ready_to_send', 'error', 'Send Error')):
            raise ValidationError(
                _("Please select only 'Ready to Send' or 'Error' queue entries to perform this action."))
        self.write({'state': 'cancelled'})

    def _check_status(self):
        print("\n_check_status() >>>>")
        for obj in self:
            access_point = self.env['peppol.access.point.sg'].sudo().search([('company_id', '=', obj.company_id.id)],
                                                                            order="create_date")
            if not access_point:
                obj.write({'state': 'error'})
                log = _("Access Point configuration is not defined.")
                obj.message_post(body=log)
                continue
            base_url = access_point.endpoint
            api_version = access_point.api_version
            base64_string = access_point.get_basic_auth_token()  # TODO: Dont calculate but instead calculate and store as one time.
            timeout = self.env['ir.config_parameter'].sudo().get_param('api_timeout', default='20')
            # headers = {
            #     "Accept": "*/*",
            #     "Authorization": "Basic {}".format(base64_string),
            # }
            headers = {
                "Accept": "*/*",
                "Authorization": f"Bearer {access_point.access_token}",
            }

            try:
                response = requests.get(
                    '%s/api/business/%s/order-response-advanced/peppol-order-response-advanced/%s' % (base_url, api_version, obj.client_ref),
                    headers=headers,
                    timeout=int(timeout))
            except requests.exceptions.Timeout:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>A timeout occured while trying to perform the Check Sent '
                    'Document status Api.')
                obj.message_post(body=log)
                continue
            except requests.exceptions.HTTPError:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>HTTP error occurred while trying to perform the Check Sent '
                    'Document status Api.')
                obj.message_post(body=log)
                continue
            except Exception as e:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>The Check Document status Api is not reachable, '
                    'please try again later.<br/>Exception handler details: %s') % (repr(e))
                obj.message_post(body=log)
                continue
            status_code = response.status_code
            response_data = json.loads(response.text)
            print("\nstatus_code ===", status_code)
            print("response_data ===", response_data)
            if status_code == 200 and isinstance(response_data, dict):
                if response_data['info'][0].get('status') == 'Send Success':
                    print(" iffffff")
                    state = response_data['status'] if response_data['status'] == 'Completed' else \
                        response_data['info'][0].get('status')
                else:
                    print("else")
                    state = response_data['info'][0].get('status')
                    print("state >>>>>", state)

                obj.write({'state': state,
                           'status_message': response_data['info'][0].get('statusMessage'),
                           'invalidated': 'yes' if response_data['info'][0].get('invalidated') is True else 'no',
                           'extracted_senderid': response_data['info'][0].get('sender'),
                           'extracted_receiverid': response_data['info'][0].get('receiver'),
                           'extracted_docno': response_data['info'][0].get('documentNo'),
                           'instance_id': response_data['info'][0].get('instanceId'),
                           'docstatusapi_json_response': response_data})
            else:
                obj.write({'state': 'error'})
                log = _(
                    "Check Document status Api responded with status code: <b>{} {}</b><br/>{}".format(status_code,
                                                                                                       ERROR_RESPONSES_DIC.get(
                                                                                                           status_code,
                                                                                                           ''),
                                                                                                       response_data))
                obj.message_post(body=log)

    def check_clarification_required(self):
        for obj in self:
            if obj.response_code in ['UQ', 'RE', 'CA'] and not obj.status_ids:
                raise ValidationError(
                    "Clarification is mandatory for the selected status. \nClarification may be given as a code, a description or both. If both are used, they must indicate the same clarification.\nPlease do the required updations.")


# class InvoiceResponseStatus(models.Model):
#     _name = "invoice.response.status"
#
#     inv_response_out_id = fields.Many2one('invoice.responses.queue.out')
#     inv_response_in_id = fields.Many2one('invoice.responses.queue.in')
#     list_identifier = fields.Selection([('OPStatusAction', 'Actions'), ('OPStatusReason', 'Reasons')],
#                                        string='List Identifier')
#     clarification_code_id = fields.Many2one("clarification.codes", string="Clarification Code")
#     clarification_description = fields.Text('Clarification Description')
#     condition_code_ids = fields.One2many('status.condition.codes', 'response_status_id', 'Condition Codes')
#
#     @api.onchange('list_identifier')
#     def onchange_list_identifier(self):
#         self.clarification_code_id = False
#         self.clarification_description = False


# class StatusConditionCodes(models.Model):
#     _name = "status.condition.codes"
#     _rec_name = 'condition_code'
#
#     condition_code = fields.Char('Condition Code')
#     condition_value = fields.Char('Condition Value')
#     response_status_id = fields.Many2one('invoice.response.status')


# class ClarificationCodes(models.Model):
#     _name = "clarification.codes"
#     _description = "Clarification Codes"
#
#     name = fields.Char(string="Name")
#     status_type = fields.Selection([('OPStatusAction', 'Actions'), ('OPStatusReason', 'Reasons')], string="Status Type")
#     description = fields.Text(string="Description of the Code")
#     code = fields.Char(string="Technical Code")

