import base64
import hashlib
import hmac
import json
import logging
import requests
import traceback
from collections import defaultdict
from odoo.exceptions import ValidationError

from odoo import api, models, fields, _
from odoo.addons.iap.tools.iap_tools import InsufficientCreditError

logger = logging.getLogger(__name__)

SELECTION_PEPPOL_QUEUE_OUT_STATE = [
    ('ready_to_send', 'Ready to Send'),
    ('Pending', 'Pending'),
    ('Processing', 'Processing'),
    ('Send Success', 'Send Success'),
    ('Send Error', 'Send Error'),
    ('Receive Success', 'Receive Success'),
    ('Completed', 'Completed'),
    ('error', 'Failed'),
    ('cancelled', 'Cancelled'),
]

ERROR_RESPONSES_DIC = {
    400: 'Bad Request',
    401: 'Unauthorized',
    404: 'Not Found',
    403: 'Forbidden',
    405: 'Method not allowed'
}

class OrderBalanceQueueOut(models.Model):
    _name = "order.balance.queue.out"
    _description = "Outgoing Balance Orders Queue"
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = "create_date desc, id desc"

    name = fields.Char(string="Name", compute="_compute_name", store=True)
    order_id = fields.Many2one("purchase.order", string="Purchase Order")
    sale_order_id = fields.Many2one("sale.order", string="Sale Order")
    partner_id = fields.Many2one('res.partner', related='order_id.partner_id', string='Vendor', store=True)
    client_ref = fields.Char('Client Ref',
                             help="Unique client reference for this upload. Generated by ERP and used in further API Requests.")
    state = fields.Selection(SELECTION_PEPPOL_QUEUE_OUT_STATE, string="Status", default='ready_to_send', readonly=True,
                             tracking=1, index=True)
    issue_date = fields.Datetime(string="Issue Datetime")

    company_id = fields.Many2one('res.company', string="Company", compute="_compute_company", store=True)
    sent = fields.Boolean(string="Sent", readonly=True)

    server_receipt = fields.Char("Server Receipt",
                                 help="Unique server receipt number generated for the document(s) upload. This is received from the DataPost API extracted from the JSON response.")
    status_message = fields.Text('Status Message', default=False, tracking=1,
                                 help="Detailed description for the status.")
    upload_time = fields.Char('Document uploaded/received time')
    extracted_senderid = fields.Char('Sender ID', help="Sender id extracted from the uploaded xml", tracking=1)
    extracted_receiverid = fields.Char('Receiver ID', help="Receiver id extracted from the uploaded xml", tracking=1)
    extracted_totamount = fields.Char('Total Amount', help="Document total amount extracted from the uploaded xml",
                                      tracking=1)
    extracted_docno = fields.Char('Document No', help="Document number extracted from the uploaded xml", tracking=1)
    sentapi_json_response = fields.Text('Send Documents API Response',
                                        help="We track the response and store in this record for the sake of reference.")
    invalidated = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Invalidated Document",
                                   help="true denotes an Invalidated document. Documents become invalidated when a new document with the same Document number received again.",
                                   tracking=1)
    instance_id = fields.Char('Instance ID',
                              help="Generated unique id for the document when sending to the peppol network.")
    docstatusapi_json_response = fields.Text('Document Status API Response',
                                             help="We track the response and store in this record for the sake of reference.")
    xml_data = fields.Text("XML Order Data", help="For Technical Use only")
    attachment_ids = fields.Many2many('ir.attachment', 'order_balance_queue_out_attach_rel', 'queue_id', 'attachment_id', string='Documents')
    response_status_code = fields.Selection([('AB', 'Message acknowledgement'), ('AP', 'Accepted'), ('RE', 'Rejected'),
                                      ('CA', 'Conditionally accepted')], string="Response", readonly=True)
    received_order_responses_count = fields.Integer(string="Received Order Response Count",compute="_compute_order_response_count")



    # _sql_constraints = [
    #     (
    #         'mode_document_unique',
    #         'UNIQUE(order_id)',
    #         'Can only send single Document to PEPPOL once.',
    #     ),
    # ]


    @api.depends('order_id')
    def _compute_name(self):
        for entry in self:
            entry.name = "%s" % entry.order_id.name

    @api.depends('order_id')
    def _compute_company(self):
        for entry in self:
            document = entry.order_id
            try:
                company = document and document.company_id or None
            except AttributeError:  # Document doesn't have company_id
                company = None
            entry.company_id = company

    def action_force_cancel(self):
        self.write({'state': 'cancelled'})

    @api.model
    def _cron_process_documents(self):
        to_check = self.search([('state', 'in', ['Pending', 'Processing', 'Send Success'])])
        if to_check:
            to_check._check_status()

        to_send = self.search([('state', '=', 'ready_to_send')])
        if to_send:
            to_send._send()

    def _send(self):
        print("\n_send() >>>>>")
        for obj in self:
            xml_string = ''
            order_obj = obj.order_id
            access_point = self.env['peppol.access.point.sg'].sudo().search([('company_id','=',obj.company_id.id)], order="create_date")
            if not access_point:
                obj.write({'state': 'error'})
                log = _("Access Point configuration is not defined")
                obj.message_post(body=log)
                continue
            try:

                xml_string = order_obj.generate_ord_balance_ubl_xml_string(queue_obj=obj)

                print("\n\nxml_string ===",xml_string)

                base_url = access_point.endpoint
                api_version = access_point.api_version
                base64_string = access_point.get_basic_auth_token()
                client_ref = access_point.get_client_ref()
                timeout = self.env['ir.config_parameter'].sudo().get_param('api_timeout', default='20')
                # headers = {
                #     "Accept": "*/*",
                #     "Authorization": "Basic {}".format(base64_string),
                # }
                headers = {
                    "Accept": "*/*",
                    "Authorization": f"Bearer {access_point.access_token}",
                }
                files = {
                    'document': (obj.order_id.name + '.xml', xml_string.decode('utf-8'), 'application/xml')
                }
                try:
                    response = requests.post(
                        '%s/api/business/%s/order-balance/peppol-order-balance/%s' % (base_url, api_version, client_ref),
                        files=files,
                        headers=headers,
                        timeout=int(timeout))
                    print("response",response)
                except requests.exceptions.Timeout:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _(
                        '<b>An Exception has arised.</b><br/>A timeout occured while trying to perform the Send '
                        'Documents API.')
                    obj.message_post(body=log)
                    continue
                except requests.exceptions.HTTPError:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _(
                        '<b>An Exception has arised.</b><br/>HTTP error occurred while trying to perform the Send '
                        'Documents API.')
                    obj.message_post(body=log)
                    continue
                except Exception as e:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _(
                        '<b>An Exception has arised.</b><br/>The Send Documents API is not reachable, please try '
                        'again later.<br/> '
                        'Exception handler details: %s') % (
                              repr(e))
                    obj.message_post(body=log)
                    continue
                status_code = response.status_code
                try:
                    response_data = json.loads(response.text)
                    print("response_data",response_data)
                except:
                    response_data = response.text
                if status_code == 200 and isinstance(response_data, dict):
                    report = self.env.ref('purchase.action_report_purchase_order')._render_qweb_pdf(obj.order_id.id)
                    attach_ids = [(2, attach_obj.id) for attach_obj in obj.attachment_ids]
                    if attach_ids:
                        obj.write({'attachment_ids': attach_ids})
                    obj.write({'state': response_data['info'][0].get('status'),
                               'client_ref': client_ref,
                               'server_receipt': response_data.get('serverReceipt'),
                               'status_message': response_data['info'][0].get('statusMessage'),
                               'upload_time': response_data['info'][0].get('uploadTime'),
                               'extracted_senderid': response_data['info'][0].get('sender'),
                               'extracted_receiverid': response_data['info'][0].get('receiver'),
                               'extracted_totamount': response_data['info'][0].get('amount'),
                               'extracted_docno': response_data['info'][0].get('documentNo'),
                               'invalidated': 'yes' if response_data['info'][0].get('invalidated') == True else 'no',
                               'sentapi_json_response': response_data,
                               'sent': True,
                               'xml_data': xml_string,
                               'attachment_ids': [(0, 0, {
                                   'type': 'binary',
                                   'name': "Order-" + obj.order_id.name + ".pdf",
                                   'datas': str(base64.b64encode(report[0]), 'UTF-8'),
                                   'mimetype': 'application/pdf',
                                   'res_model': 'peppol.queue.out',
                                   'res_id': obj.order_id.id
                               })]})
                else:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _("<b>Send Documents API responded as {} {}</b><br/>{}".format(status_code,
                                                                                         ERROR_RESPONSES_DIC.get(
                                                                                             status_code, ''),
                                                                                         response_data))
                    obj.message_post(body=log)
            except Exception as e:
                obj.write({'state': 'error', 'xml_data': xml_string})
                log = _('<b>A Critical Error has arised.</b><br/>Traceback::%s') % (traceback.format_exc())
                obj.message_post(body=log)

    def _check_status(self):
        for obj in self:
            access_point = self.env['peppol.access.point.sg'].sudo().search([('company_id','=',obj.company_id.id)], order="create_date")
            if not access_point:
                obj.write({'state': 'error'})
                log = _("Access Point configuration is not defined")
                obj.message_post(body=log)
                continue
            base_url = access_point.endpoint
            api_version = access_point.api_version
            base64_string = access_point.get_basic_auth_token()  # TODO: Dont calculate but instead calculate and store as one time.
            timeout = self.env['ir.config_parameter'].sudo().get_param('api_timeout', default='20')
            # headers = {
            #     "Accept": "*/*",
            #     "Authorization": "Basic {}".format(base64_string),
            # }
            headers = {
                "Accept": "*/*",
                "Authorization": f"Bearer {access_point.access_token}",
            }
            try:
                response = requests.get(
                    '%s/api/business/%s/order-balance/peppol-order-balance/%s' % (base_url, api_version, obj.client_ref),
                    headers=headers,
                    timeout=int(timeout))
            except requests.exceptions.Timeout:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>A timeout occured while trying to perform the Check Sent '
                    'Document status Api.')
                obj.message_post(body=log)
                continue
            except requests.exceptions.HTTPError:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>HTTP error occurred while trying to perform the Check Sent '
                    'Document status Api.')
                obj.message_post(body=log)
                continue
            except Exception as e:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>The Check Document status Api is not reachable, '
                    'please try again later.<br/>Exception handler details: %s') % (repr(e))
                obj.message_post(body=log)
                continue
            status_code = response.status_code
            try:
                response_data = json.loads(response.text)
            except:
                response_data = response.text
            if status_code == 200 and isinstance(response_data, dict):
                if response_data['info'][0].get('status') == 'Send Success':
                    state = response_data['status'] if response_data['status'] == 'Completed' else \
                        response_data['info'][0].get('status')
                else:
                    state = response_data['info'][0].get('status')
                obj.write({'state': state,
                           'status_message': response_data['info'][0].get('statusMessage'),
                           'invalidated': 'yes' if response_data['info'][0].get('invalidated') is True else 'no',
                           'extracted_senderid': response_data['info'][0].get('sender'),
                           'extracted_receiverid': response_data['info'][0].get('receiver'),
                           'extracted_totamount': response_data['info'][0].get('amount'),
                           'extracted_docno': response_data['info'][0].get('documentNo'),
                           'instance_id': response_data['info'][0].get('instanceId'),
                           'docstatusapi_json_response': response_data})
            else:
                obj.write({'state': 'error'})
                log = _(
                    "Check Document status Api responded with status code: <b>{} {}</b><br/>{}".format(status_code,
                                                                                                            ERROR_RESPONSES_DIC.get(
                                                                                                                status_code,
                                                                                                                ''),
                                                                                                            response_data))
                obj.message_post(body=log)


    def action_send(self):
        print("q.state != 'ready_to_send' ==", self.filtered(lambda q: q.state != 'ready_to_send'))
        if self.filtered(lambda q: q.state != 'ready_to_send'):
            raise ValidationError(_("Please select only 'Ready to Send' queue entries to perform this action."))
        self._send()

    def action_check_status(self):
        if self.filtered(lambda q: q.state not in 'Pending,Processing,Send Success'.split(',')):
            raise ValidationError(
                _("Please select only either of the following states queue entries for this action to perform.\n "
                  "'Pending, Processing and Send Success'. "))
        self._check_status()

    def action_retry(self):
        if self.filtered(lambda q: q.state not in 'error,Send Error'.split(',')):
            raise ValidationError(
                _("Please select only 'Error', 'Send Error' & 'Cancelled' queue entries to perform this action."))
        # check_status_api = self.filtered(lambda q: q.sent and q.state in ['error'])
        # check_status_api._check_status()

        resend_doc_api = self.filtered(lambda q: q.state in ('Send Error', 'error'))
        resend_doc_api._send()

    def action_reset(self):
        if self.filtered(lambda q: q.state not in 'error,cancelled'.split(',')):
            raise ValidationError(_("Please select only 'Error' or 'Cancelled' queue entries to perform this action."))
        self.write({'state': 'ready_to_send'})

    def action_force_cancel(self):
        self.write({'state': 'cancelled'})

    def action_cancel(self):
        if self.filtered(lambda q: q.state not in ('ready_to_send', 'error', 'Send Error')):
            raise ValidationError(
                _("Please select only 'Ready to Send' or 'Error' queue entries to perform this action."))
        self.write({'state': 'cancelled'})

    def action_test(self):
        return False

    def unlink(self):
        for line in self:
            if line.state not in ('ready_to_send', 'cancelled'):
                raise ValidationError(
                    _("You cannot delete the records other than 'Ready to Send' or 'Cancelled' states."))
        return super(OrderBalanceQueueOut, self).unlink()

    def action_view_order_response_queue_in(self):
        name = 'Incoming Order Responses'
        return {
            'type': 'ir.actions.act_window',
            'name': name,
            'res_model': 'order.responses.queue.in',
            'domain': [('order_queue_out_id', '=', self.ids)],
            'view_mode': 'tree,form',
            'target': 'current',
        }

    def _compute_order_response_count(self):
        for rec in self:
            order_response_count = self.env['order.responses.queue.in'].search_count(
                [('order_queue_out_id', '=', rec.id)])
            rec.received_order_responses_count = order_response_count

    def _add_to_queue(self, document):
        document.ensure_one()
        entry = self.search([
            ('order_id', '=', document.id),
        ])
        if entry:
            return entry
        # Check if Peppol ID is provided on the form or not
        # if not document.partner_id.peppol_identifier:
        #     raise ValidationError(_("You cannot send the record %s to Peppol.\nPeppol Identifier for the Customer %s "
        #                             "is not set.") % (document.name, document.partner_id.name))
        # for line in document.order_line:
        #     tax = line.taxes_id
        #     if not tax.unece_categ_id:
        #         raise ValidationError(_("Missing UNECE Tax Category on tax '%s'" % tax.name))
        return self.create({
            'sale_order_id': document.id,
        })