from odoo import models, fields, api, _
import base64
import requests, json
import uuid
from lxml import etree
import xml.etree.ElementTree as ET
from xml.dom import minidom
from datetime import datetime
from odoo.exceptions import ValidationError

ERROR_RESPONSES_DIC = {
    400: 'Bad Request',
    401: 'Unauthorized',
    404: 'Not Found',
    403: 'Forbidden',
    405: 'Method not allowed'
}

NAMESPACES = {
            'sbdh': "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader",
            'ubl': "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2",
            'cac': "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
            'cbc': "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
        }
SELECTION_PEPPOL_PCP_STATE = [
    ('ready_to_send', 'Ready to Send'),
    ('Pending', 'Pending'),
    ('Processing', 'Processing'),
    ('Send Success', 'Send Success'),
    ('Send Error', 'Send Error'),
    ('Receive Success', 'Receive Success'),
    ('Completed', 'Completed'),
    ('error', 'Failed'),
    ('cancelled', 'Cancelled'),
]

class PCPOutgoinInvoices(models.Model):
    _name = 'pcp.outgoing.invoices'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _description = 'Aggregated Petty Cash Purchase'

    name = fields.Char(string="Invoice Number", required=True, copy=False, readonly=True, default='New')
    uuid = fields.Char(string="UUID", default=lambda self: str(uuid.uuid4()), readonly=True)
    company_id = fields.Many2one('res.company', string="Company", required=True, default=lambda self: self.env.company)
    partner_id = fields.Many2one('res.partner', string="Sender", related='company_id.partner_id', readonly=True)
    receiver = fields.Char(string="Receiver", default='IRAS', readonly=True)
    invoice_date = fields.Date(string="Issue Date")

    tax_amount = fields.Monetary(string="Tax Amount")
    taxable_amount = fields.Monetary(string="Taxable Amount")
    tax_inclusive_amount = fields.Monetary(string="Tax Inclusive Amount")
    note = fields.Text(string="Note")
    currency_id = fields.Many2one('res.currency', string="Currency", default=lambda self: self.env.company.currency_id,
                                  readonly=True)

    state = fields.Selection(SELECTION_PEPPOL_PCP_STATE, string="Status", default='ready_to_send', readonly=True,
                             tracking=1, index=True)
    xml_data = fields.Text("XML Invoice Data", help="For Technical Use only")

    message = fields.Char(string="Message")
    success = fields.Char(string="Success")
    version = fields.Char(string="Version")
    correlation_id = fields.Char(string="Correlation ID")
    acknowledgement_id = fields.Char(string="Acknowledgement ID")
    sender_id = fields.Char(string="Sender ID")
    transmission_id = fields.Char(string="Transmission ID")
    received = fields.Char(string="Received")
    progress = fields.Char(string="Progress")
    error_code = fields.Char(string="Error Code")
    errors = fields.Char(string="Errors")
    code = fields.Char(string="Code")
    client_ref = fields.Char('Client Ref',
                             help="Unique client reference for this upload. Generated by ERP and used in further API Requests.")
    server_receipt = fields.Char(string="Server Receipt")
    status = fields.Char(string="Response Status")

    def action_retry(self):
        if self.filtered(lambda q: q.state not in 'error,Send Error'.split(',')):
            raise ValidationError(
                _("Please select only 'Error', 'Send Error' & 'Cancelled' queue entries to perform this action."))
        check_status_api = self.filtered(lambda q: q.state and q.state in ['error'])
        check_status_api._check_status()

        resend_doc_api = self.filtered(lambda q: q.state in ('Send Error', 'error'))
        if resend_doc_api.peppol_c5_purchase_inv or resend_doc_api.nonpeppol_c5_purchase_inv:
            resend_doc_api._send()
        else:
            resend_doc_api._c5_nonpeppol_send()


    def action_reset(self):
        if self.filtered(lambda q: q.state not in 'error,cancelled'.split(',')):
            raise ValidationError(_("Please select only 'Error' or 'Cancelled' queue entries to perform this action."))
        self.write({'state': 'ready_to_send'})

    def action_cancel(self):
        if self.filtered(lambda q: q.state not in ('ready_to_send', 'error', 'Send Error')):
            raise ValidationError(
                _("Please select only 'Ready to Send' or 'Error' queue entries to perform this action."))
        self.write({'state': 'cancelled'})

    def action_check_status(self):
        if self.filtered(lambda q: q.state not in 'Pending,Processing,Send Success'.split(',')):
            raise ValidationError(
                _("Please select only either of the following states queue entries for this action to perform.\n "
                  "'Pending, Processing and Send Success'. "))
        self._check_status()


    @api.model
    def create(self, vals):
        if vals.get('name', ('New')) == ('New'):
            vals['name'] = self.env['ir.sequence'].next_by_code('pcp.outgoing.invoices') or ('New')
        return super(PCPOutgoinInvoices, self).create(vals)

    def action_send(self):
        peppol_xml = self._generate_xml_peppol()
        self._send_peppol(peppol_xml)

    def _generate_xml_peppol(self):
        root = ET.Element("StandardBusinessDocument", xmlns=NAMESPACES['sbdh'])
        header = ET.SubElement(root, "StandardBusinessDocumentHeader")
        ET.SubElement(header, "HeaderVersion").text = "1.0"

        sender = ET.SubElement(header, "Sender")
        ET.SubElement(sender, "Identifier", Authority="iso6523-actorid-upis").text = self.partner_id.peppol_identifier

        receiver = ET.SubElement(header, "Receiver")
        ET.SubElement(receiver, "Identifier", Authority="iso6523-actorid-upis").text = "IRAS"

        doc_id = ET.SubElement(header, "DocumentIdentification")
        ET.SubElement(doc_id, "Standard").text = "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
        ET.SubElement(doc_id, "TypeVersion").text = "2.1"
        ET.SubElement(doc_id, "InstanceIdentifier").text = self.uuid
        ET.SubElement(doc_id, "Type").text = "Invoice"
        ET.SubElement(doc_id, "CreationDateAndTime").text = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%fZ")

        business_scope = ET.SubElement(header, "BusinessScope")
        scope1 = ET.SubElement(business_scope, "Scope")
        ET.SubElement(scope1, "Type").text = "DOCUMENTID"
        ET.SubElement(scope1,
                      "InstanceIdentifier").text = "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:peppol:pint:billing-1@sg-1:LocalTaxInvoice:sg:1.0::2.1"
        ET.SubElement(scope1, "Identifier").text = "peppol-doctype-wildcard"

        scope2 = ET.SubElement(business_scope, "Scope")
        ET.SubElement(scope2, "Type").text = "PROCESSID"
        ET.SubElement(scope2, "InstanceIdentifier").text = "urn:peppol:bis:billing"
        ET.SubElement(scope2, "Identifier").text = "cenbii-procid-ubl"

        scope3 = ET.SubElement(business_scope, "Scope")
        ET.SubElement(scope3, "Type").text = "Document_UUID"
        ET.SubElement(scope3, "InstanceIdentifier").text = self.uuid

        invoice = ET.SubElement(root, "Invoice", {
            "xmlns": "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2",
            "xmlns:cac": "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
            "xmlns:cbc": "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
            "xmlns:ccts": "urn:un:unece:uncefact:documentation:2",
            "xmlns:ext": "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2",
            "xmlns:qdt": "urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2",
            "xmlns:udt": "urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2",
            "xmlns:xsd": "http://www.w3.org/2001/XMLSchema",
            "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance"
        })
        ET.SubElement(invoice, "cbc:CustomizationID").text = 'urn:peppol:pint:billing-1@sg-1:LocalTaxInvoice:sg:1.0'
        ET.SubElement(invoice, "cbc:ProfileID").text = 'urn:peppol:bis:Payables'
        ET.SubElement(invoice, "cbc:ID").text = self.name
        ET.SubElement(invoice, "cbc:UUID").text = self.uuid
        ET.SubElement(invoice, "cbc:IssueDate").text = self.invoice_date.strftime("%Y-%m-%d")
        ET.SubElement(invoice, "cbc:DueDate").text = self.invoice_date.strftime("%Y-%m-%d")
        ET.SubElement(invoice, "cbc:InvoiceTypeCode").text = "380"
        ET.SubElement(invoice, "cbc:Note").text = self.note
        ET.SubElement(invoice, "cbc:DocumentCurrencyCode").text = "SGD"

        supplier_party = ET.SubElement(invoice, "cac:AccountingSupplierParty")
        supplier_party_info = ET.SubElement(supplier_party, "cac:Party")
        ET.SubElement(supplier_party_info, "cbc:EndpointID", schemeID="0195").text = "PCP"
        supplier_address = ET.SubElement(supplier_party_info, "cac:PostalAddress")
        ET.SubElement(supplier_address, "cbc:StreetName").text = self.partner_id.street
        ET.SubElement(supplier_address, "cbc:CityName").text = self.partner_id.city
        ET.SubElement(supplier_address, "cbc:PostalZone").text = self.partner_id.zip
        ET.SubElement(supplier_address, "cbc:CountrySubentity").text = self.partner_id.country_id.name
        country = ET.SubElement(supplier_address, "cac:Country")
        ET.SubElement(country, "cbc:IdentificationCode").text = self.partner_id.country_id.code
        tax_scheme = ET.SubElement(supplier_party_info, "cac:PartyTaxScheme")
        ET.SubElement(tax_scheme, "cbc:CompanyID").text = "PCP"
        tax_scheme_asp_info = ET.SubElement(tax_scheme, "cac:TaxScheme")
        ET.SubElement(tax_scheme_asp_info, "cbc:ID").text = "GST"
        legal_entity = ET.SubElement(supplier_party_info, "cac:PartyLegalEntity")
        ET.SubElement(legal_entity, "cbc:RegistrationName").text = "PCP"
        ET.SubElement(legal_entity, "cbc:CompanyID", schemeID="0195").text = "PCP"

        customer_party = ET.SubElement(invoice, "cac:AccountingCustomerParty")
        customer_party_info = ET.SubElement(customer_party, "cac:Party")
        ET.SubElement(customer_party_info, "cbc:EndpointID", schemeID="0195").text = self.partner_id.peppol_identifier
        customer_address = ET.SubElement(customer_party_info, "cac:PostalAddress")
        ET.SubElement(customer_address, "cbc:StreetName").text = self.partner_id.street
        ET.SubElement(customer_address, "cbc:AdditionalStreetName").text = self.partner_id.street2
        ET.SubElement(customer_address, "cbc:CityName").text = self.partner_id.city
        ET.SubElement(customer_address, "cbc:PostalZone").text = self.partner_id.zip
        ET.SubElement(customer_address, "cbc:CountrySubentity").text = self.partner_id.country_id.name
        country = ET.SubElement(customer_address, "cac:Country")
        ET.SubElement(country, "cbc:IdentificationCode").text = self.partner_id.country_id.code
        if self.partner_id.vat:
            tax_scheme = ET.SubElement(customer_party_info, "cac:PartyTaxScheme")
            ET.SubElement(tax_scheme, "cbc:CompanyID").text = self.partner_id.vat
            tax_scheme_info = ET.SubElement(tax_scheme, "cac:TaxScheme")
            ET.SubElement(tax_scheme_info, "cbc:ID").text = "GST"

        legal_entity = ET.SubElement(customer_party_info, "cac:PartyLegalEntity")
        ET.SubElement(legal_entity, "cbc:RegistrationName").text = "Libero Done Pte Ltd"
        ET.SubElement(legal_entity, "cbc:CompanyID", schemeID="0195").text = self.partner_id.l10n_sg_unique_entity_number

        tax_total = ET.SubElement(invoice, "cac:TaxTotal")
        ET.SubElement(tax_total, "cbc:TaxAmount", currencyID="SGD").text = str(self.tax_amount)
        tax_subtotal = ET.SubElement(tax_total, "cac:TaxSubtotal")
        ET.SubElement(tax_subtotal, "cbc:TaxableAmount", currencyID="SGD").text = str(self.taxable_amount)
        ET.SubElement(tax_subtotal, "cbc:TaxAmount", currencyID="SGD").text = str(self.tax_amount)
        tax_category = ET.SubElement(tax_subtotal, "cac:TaxCategory")
        ET.SubElement(tax_category, "cbc:ID").text = "TX"
        ET.SubElement(tax_category, "cbc:Percent").text = "9"
        tax_scheme = ET.SubElement(tax_category, "cac:TaxScheme")
        ET.SubElement(tax_scheme, "cbc:ID").text = "GST"

        legal_monetary_total = ET.SubElement(invoice, "cac:LegalMonetaryTotal")
        ET.SubElement(legal_monetary_total, "cbc:LineExtensionAmount", currencyID="SGD").text = str(self.taxable_amount)
        ET.SubElement(legal_monetary_total, "cbc:TaxExclusiveAmount", currencyID="SGD").text = str(self.taxable_amount)
        ET.SubElement(legal_monetary_total, "cbc:TaxInclusiveAmount", currencyID="SGD").text = str(self.tax_inclusive_amount)
        ET.SubElement(legal_monetary_total, "cbc:PayableAmount", currencyID="SGD").text = str(self.tax_inclusive_amount)

        invoice_line = ET.SubElement(invoice, "cac:InvoiceLine")
        ET.SubElement(invoice_line, "cbc:ID").text = "1"
        ET.SubElement(invoice_line, "cbc:InvoicedQuantity", unitCode="LOT").text = "1"
        ET.SubElement(invoice_line, "cbc:LineExtensionAmount", currencyID="SGD").text = str(self.taxable_amount)

        item = ET.SubElement(invoice_line, "cac:Item")
        ET.SubElement(item, "cbc:Name").text = "PCP"
        classified_tax_category = ET.SubElement(item, "cac:ClassifiedTaxCategory")
        ET.SubElement(classified_tax_category, "cbc:ID").text = "TX"
        ET.SubElement(classified_tax_category, "cbc:Percent").text = "9"
        tax_scheme = ET.SubElement(classified_tax_category, "cac:TaxScheme")
        ET.SubElement(tax_scheme, "cbc:ID").text = "GST"

        price = ET.SubElement(invoice_line, "cac:Price")
        ET.SubElement(price, "cbc:PriceAmount", currencyID="SGD").text = str(self.taxable_amount)
        ET.SubElement(price, "cbc:BaseQuantity").text = "1"

        xml_string = ET.tostring(root, encoding="utf-8", method="xml").decode("utf-8")
        xml_pretty = minidom.parseString(xml_string).toprettyxml(indent="  ")
        xml_final_string = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' + "\n".join(
            xml_pretty.split("\n")[1:])

        return xml_final_string

    def _send_peppol(self, peppol_xml):
        """Sends the generated PEPPOL XML to the Datapost API."""
        access_point = self.env['peppol.access.point.sg'].sudo().search([('company_id', '=', self.company_id.id)],
                                                                        order="create_date")
        document_type = 'purchase-invoices'
        document_format = 'non-peppol'
        base_url = access_point.endpoint
        api_version = access_point.api_version
        client_ref = access_point.get_uuid()
        timeout = self.env['ir.config_parameter'].sudo().get_param('api_timeout', default='20')
        headers = {
            "Authorization": f"Bearer {access_point.access_token}",
            "Accept": "application/json",
        }
        files = {
            'document': (f"{self.name}.xml", peppol_xml, 'application/xml')
        }
        print("files>>>>>", files)
        # request_url = f"{base_url}/api/submit/{api_version}/{document_type}/{document_format}/{client_ref}"
        request_url = f"{base_url}/api/submit/{document_type}/{document_format}/{client_ref}"
        try:
            print('%s/business/%s/%s/%s/%s?????', request_url)
            response = requests.post(request_url, headers=headers, files=files)
            print("response", response, response.status_code)
        except requests.exceptions.Timeout:
            self.write({'state': 'error', 'xml_data': peppol_xml})
            log = _(
                '<b>An Exception has arised.</b><br/>A timeout occured while trying to perform the Send '
                'Documents API.')
            self.message_post(body=log)
        except requests.exceptions.HTTPError:
            self.write({'state': 'error', 'xml_data': peppol_xml})
            log = _(
                '<b>An Exception has arised.</b><br/>HTTP error occurred while trying to perform the Send '
                'Documents API.')
            self.message_post(body=log)
        except Exception as e:
            self.write({'state': 'error', 'xml_data': peppol_xml})
            log = _(
                '<b>An Exception has arised.</b><br/>The Send Documents API is not reachable, please try '
                'again later.<br/> '
                'Exception handler details: %s') % (
                      repr(e))
            self.message_post(body=log)
        status_code = response.status_code
        try:
            response_data = json.loads(response.text)
            print("response_data", response_data)
        except:
            response_data = response.text
        print('\n\n\n\nstatus_code', status_code)
        if status_code == 200 and isinstance(response_data, dict):
            get_response_submit = response_data['irasSubmitResponseDto'][0]
            self.write({
                'state': 'Send Success' if get_response_submit.get('success') == True else False,
                'client_ref': response_data.get('clientRef'),
                'server_receipt': response_data.get('serverReceipt'),
                'status': response_data.get('status'),
                'message': get_response_submit.get('message'),
                'success': get_response_submit.get('success'),
                'version': get_response_submit.get('version'),
                'correlation_id': get_response_submit.get('correlationId'),
                'acknowledgement_id': get_response_submit.get('acknowledgementId'),
                'xml_data': peppol_xml,
                'sender_id': get_response_submit.get('senderId'),
                'transmission_id': get_response_submit.get('transmissionId'),
                'received': get_response_submit.get('received'),
                'progress': get_response_submit.get('progress'),
                'error_code': get_response_submit.get('errorCode'),
                'errors': get_response_submit.get('errors'),
                'code': get_response_submit.get('code'),
            })
        else:
            self.write({'state': 'error', 'xml_data': peppol_xml})
            log = _("<b>Send Documents API responded as {} {}</b><br/>{}".format(status_code,
                                                                                 ERROR_RESPONSES_DIC.get(
                                                                                     status_code, ''),
                                                                                 response_data))
            self.message_post(body=log)

    def _check_status(self):
        for obj in self:
            access_point = self.env['peppol.access.point.sg'].sudo().search([('company_id','=',obj.company_id.id)], order="create_date")
            if not access_point:
                obj.write({'state': 'error'})
                log = _("Access Point configuration is not defined")
                obj.message_post(body=log)
                continue
            base_url = access_point.endpoint
            api_version = access_point.api_version
            #access_token = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzODRjYTkxMzRmMmE0Njk3OTUzZWMwOThmZTAzNGQwZiIsImV4cCI6MTczOTQyMzU4NCwiaWF0IjoxNzM5NDIyOTc5fQ.x86XGYXsfDSndRzgxICAfw7-yuLEHuxsJOnD88b-kLc"
            headers = {
                "Authorization": f"Bearer {access_point.access_token}",
                "Accept": "application/json",
            }
            try:
                document_type = 'invoices'
                document_format = 'non-peppol-invoice-2'
                response = requests.get(
                    '%s/api/business/%s/%s/%s/%s' % (base_url, api_version, document_type, document_format, obj.client_ref),
                    headers=headers)
                print('\n\n\n\n\n\nreposnse_check_status_method', response)
            except requests.exceptions.Timeout:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>A timeout occured while trying to perform the Check Sent '
                    'Document status Api.')
                obj.message_post(body=log)
                continue
            except requests.exceptions.HTTPError:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>HTTP error occurred while trying to perform the Check Sent '
                    'Document status Api.')
                obj.message_post(body=log)
                continue
            except Exception as e:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>The Check Document status Api is not reachable, '
                    'please try again later.<br/>Exception handler details: %s') % (repr(e))
                obj.message_post(body=log)
                continue
            status_code = response.status_code
            try:
                response_data = json.loads(response.text)
            except:
                response_data = response.text
            if status_code == 200 and isinstance(response_data, dict):
                if response_data.get('status') == 'Send Success':
                    state = response_data['status'] if response_data['status'] == 'Completed' else \
                        response_data['info'][0].get('status')
                else:
                    state = response_data.get('status')
                obj.write({
                            'state': state,
                            'client_ref': response_data.get('clientRef'),
                            'server_receipt': response_data.get('serverReceipt'),
                            'status': response_data.get('status'),
                            'message': response_data['info'][0].get('statusMessage'),
                            'sender_id': response_data['info'][0].get('sender'),
                            'transmission_id': response_data['info'][0].get('irasTransmissionId'),
                            'acknowledgement_id': response_data['info'][0].get('irasAcknowledgementId'),
                            'correlation_id': response_data['info'][0].get('correlationId'),
                            'received': response_data['info'][0].get('received'),
                        })
                print("obj >>>>",obj)
            else:
                obj.write({'state': 'error'})
                log = _(
                    "Check Document status Api responded with status code: <b>{} {}</b><br/>{}".format(status_code,
                                                                                                            ERROR_RESPONSES_DIC.get(
                                                                                                                status_code,
                                                                                                                ''),
                                                                                                            response_data))
                obj.message_post(body=log)
