import base64
import hashlib
import hmac
import json
import logging
import requests
import traceback
from collections import defaultdict
from odoo.exceptions import ValidationError

from odoo import api, models, fields, _
from odoo.addons.iap.tools.iap_tools import InsufficientCreditError
from lxml import etree


logger = logging.getLogger(__name__)

SELECTION_PEPPOL_QUEUE_OUT_STATE = [
    ('ready_to_send', 'Ready to Send'),
    ('Pending', 'Pending'),
    ('Processing', 'Processing'),
    ('Send Success', 'Send Success'),
    ('Send Error', 'Send Error'),
    ('Receive Success', 'Receive Success'),
    ('Completed', 'Completed'),
    ('error', 'Failed'),
    ('cancelled', 'Cancelled'),
]

ERROR_RESPONSES_DIC = {
    400: 'Bad Request',
    401: 'Unauthorized',
    404: 'Not Found',
    403: 'Forbidden',
    405: 'Method not allowed'
}


class PeppolQueueC5Out(models.Model):
    _name = "peppol.queue.c5.out"
    _description = "Outgoing Invoices/Credit Notes Queue"
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = "create_date desc, id desc"

    name = fields.Char(string="Name", compute="_compute_name", store=True)
    mode = fields.Selection([('test', 'test'), ('live', 'live')], string="Mode", readonly=True)
    document_id = fields.Integer(string="Document ID", readonly=True)
    company_id = fields.Many2one('res.company', string="Company", default=lambda self: self.env.company, store=True)
    sent = fields.Boolean(string="Sent", readonly=True)
    invoice_id = fields.Many2one("account.move", string="Invoice")
    partner_id = fields.Many2one('res.partner', related='invoice_id.partner_id', string='Customer', store=True)
    invoice_type = fields.Selection(selection=[
        ('out_invoice', 'Invoice'),
        ('out_refund', 'Credit Note'),
        ('in_invoice', 'Vendor Bill'),
        ('in_refund', 'Vendor Credit Note'),
    ], string='Type', required=True)
    state = fields.Selection(SELECTION_PEPPOL_QUEUE_OUT_STATE, string="Status", default='ready_to_send', readonly=True,
                             tracking=1, index=True)
    client_ref = fields.Char('Client Ref',
                             help="Unique client reference for this upload. Generated by ERP and used in further API Requests.")
    server_receipt = fields.Char("Server Receipt",
                                 help="Unique server receipt number generated for the document(s) upload. This is received from the DataPost API extracted from the JSON response.")
    status_message = fields.Text('Status Message', default=False, tracking=1,
                                 help="Detailed description for the status.")
    upload_time = fields.Char('Document uploaded/received time')
    extracted_correlationid = fields.Char('Correlation Id', help="Correlation id extracted from the uploaded xml", tracking=1)
    extracted_acknowledgementid = fields.Char('Acknowledgement Id', help="Acknowledgement id extracted from the uploaded xml", tracking=1)
    extracted_transmissionid = fields.Char('Transmission Id', help="Transmission id extracted from the uploaded xml", tracking=1)

    extracted_senderid = fields.Char('Sender ID', help="Sender id extracted from the uploaded xml", tracking=1)
    extracted_receiverid = fields.Char('Receiver ID', help="Receiver id extracted from the uploaded xml", tracking=1)
    extracted_totamount = fields.Char('Total Amount', help="Document total amount extracted from the uploaded xml",
                                      tracking=1)
    extracted_docno = fields.Char('Document No', help="Document number extracted from the uploaded xml", tracking=1)
    sentapi_json_response = fields.Text('Send Documents API Response',
                                        help="We track the response and store in this record for the sake of reference.")
    invalidated = fields.Selection([('yes', 'Yes'), ('no', 'No')], string="Invalidated Document",
                                   help="true denotes an Invalidated document. Documents become invalidated when a new document with the same Document number received again.",
                                   tracking=1)
    instance_id = fields.Char('Instance ID',
                              help="Generated unique id for the document when sending to the peppol network.")
    iras_status = fields.Char("IRAS Status", help="IRAS submission status of the document.")
    iras_statusinfo = fields.Text('IRAS Status Info', help="Additional information relevant to IRAS status.")
    docstatusapi_json_response = fields.Text('Document Status API Response',
                                             help="We track the response and store in this record for the sake of reference.")
    xml_data = fields.Text("XML Invoice Data", help="For Technical Use only")
    # attachment_ids = fields.Many2many('ir.attachment', 'queue_id', 'attachment_id', string='Documents')
    received_inv_responses_count = fields.Integer(string="Received Invoice Response Count")
    response_status_code = fields.Selection([('AB', 'Message acknowledgement'), ('AP', 'Accepted'),('RE', 'Rejected'), ('IP', 'In process'),('UQ', 'Under query'),
                                ('CA', 'Conditionally accepted'),('PD', 'Paid')], string="Status", readonly=True, tracking=1)
    document_type = fields.Char('Document Type')
    document_format = fields.Char('Document Format')
    error_code = fields.Char('Error Code')
    errors = fields.Text('Error')
    document_xml_type = fields.Selection([('single', 'Single'), ('bulk', 'Bulk')], string="Sub Type", default='single')
    invoice_ids = fields.Many2many('account.move', string='Invoices')
    is_peppol = fields.Boolean(string='IS Peppol', default=False)
    peppol_c5_purchase_inv = fields.Boolean(string='IS Peppol C5 Purchase Invoice', default=False)
    nonpeppol_c5_purchase_inv = fields.Boolean(string='IS NONPeppol C5 Purchase Invoice', default=False)
    progress_type = fields.Char('Progress')
    document_uuid = fields.Char("Document UUID")
    peppol_document_type = fields.Selection([('PINT','PINT'),('BIS','BIS')], string="Document Type", tracking=1)
    is_gst_register = fields.Boolean(string="GST Register", default=False)
    gst_no = fields.Char('GST NO')


    _sql_constraints = [
        (
            'mode_document_unique',
            'UNIQUE(invoice_id)',
            'Can only send single Document to PEPPOL once.',
        ),
    ]

    # @api.constrains('invoice_ids')
    # def _check_unique_invoice_ids(self):
    #     for record in self:
    #         if record.invoice_ids:
    #             existing_records = self.search([
    #                 '|', ('id', '!=', record.id),
    #                 ('invoice_ids', 'in', record.invoice_ids.ids)
    #                 ('invoice_ids', 'in', record.invoice_id.id)
    #
    #             ])
    #             if existing_records:
    #                 raise ValidationError("Can only send a single Document to PEPPOL once.")

    @api.constrains('invoice_id', 'invoice_ids')
    def _check_unique_invoice_ids(self):
        for record in self:
            invoice_ids_list = record.invoice_ids.ids
            existing_records = self.search([
                ('id', '!=', record.id),
                '|',
                ('invoice_id', 'in', invoice_ids_list + [record.invoice_id.id] if record.invoice_id else record.invoice_ids.ids),
                ('invoice_ids', 'in', invoice_ids_list + [record.invoice_id.id] if record.invoice_id else record.invoice_ids.ids)
            ])
            if existing_records:
                raise ValidationError("Can only send a single Document to PEPPOL once.")

    @api.depends('invoice_id', 'invoice_ids')
    def _compute_name(self):
        for entry in self:
            if entry.invoice_id:
                entry.name = "%s" % entry.invoice_id.name
            elif entry.invoice_ids:
                if entry.invoice_type == 'out_invoice':
                    entry.name = "Bulk Invoice/%s" % entry.id
                else:
                    entry.name = "Bulk CreditNote/%s" % entry.id

    # @api.depends('invoice_id')
    # def _compute_company(self):
    #     for entry in self:
    #         document = entry.invoice_id
    #         try:
    #             company = document and document.company_id or None
    #         except AttributeError:  # Document doesn't have company_id
    #             company = None
    #         entry.company_id = company

    def _add_to_queue(self, document):
        document.ensure_one()
        entry = self.search([
            ('invoice_id', '=', document.id),
        ])
        if entry:
            return entry
        # Check if Peppol ID is provided on the form or not
        if not document.partner_id.commercial_partner_id.peppol_identifier:
            raise ValidationError(_("You cannot send the record %s to Peppol.\nPeppol Identifier for this Contact %s "
                                    "is not set. If this contact is an individual, please try to set the Peppol ID to his/her company(Parent).") % (document.name, document.partner_id.name))
        if not document.partner_id.commercial_partner_id.country_id:
            raise ValidationError(_("The Country is not tagged to the Partner."))
        # Check if Customer is peppol registered or not
        params = self.env['ir.config_parameter'].sudo()
        peppol_endpoint = params.get_param('peppol_endpoint', default=False)
        token = params.get_param('peppol_apikey', default=False)
        electronic_address_scheme = params.get_param('electronic_address_scheme', default="0195")
        url = "{}private/api/search/exist?pid=iso6523-actorid-upis::{}:{}".format(peppol_endpoint,
                                                                                  electronic_address_scheme,
                                                                                  document.partner_id.commercial_partner_id.peppol_identifier or '')
        headers = {'Content-type': 'application/json;charset=UTF-8', 'Authorization': 'Bearer {}'.format(token)}
        try:
            response = requests.get(url, headers=headers)
            print('\n\n\nresponse', response)
            if response.status_code in (200, 204):
                pass
            elif response.status_code == 404:
                raise ValidationError(_('Customer not registered in Peppol. You cannot send the invoice to Peppol.'))
            elif response.status_code == 400:
                message = 'Bad request'
                raise ValidationError(_('400 - Bad Request'))
            else:
                raise ValidationError(_('API Responded with status code: %s') % str(response.status_code))
        except Exception as e:
            raise ValidationError(_('%s\nSomething went wrong while trying to check the Customer whether registered '
                                    'in Peppol or not.\n%s\n') % (document.name, str(e)))

        return self.create({
            'invoice_type': document.move_type,
            'invoice_id': document.id,
        })

    def action_send(self):
        if self.filtered(lambda q: q.state != 'ready_to_send'):
            raise ValidationError(_("Please select only 'Ready to Send' queue entries to perform this action."))
        # if self.peppol_c5_purchase_inv or self.nonpeppol_c5_purchase_inv:
        #     self._send() #purchase both
        self._c5_send()

    @api.model
    def _cron_process_documents(self):
        to_check = self.search([('state', 'in', ['Pending', 'Processing', 'Send Success'])])
        for check in to_check:
            if check:
                check._check_status()

        to_send = self.search([('state', '=', 'ready_to_send')])
        for send in to_send:
            if send:
                send._c5_send()

    def _send(self):
        print("_send() >>>>>")
        for obj in self:
            xml_string = ''
            invoice_obj = obj.invoice_id
            print("invoice_obj.move_type ==",invoice_obj.move_type)
            access_point = self.env['peppol.access.point.sg'].sudo().search([('company_id','=',obj.company_id.id)], order="create_date")
            print("access_point ==", access_point)
            if not access_point:
                obj.write({'state': 'error'})
                log = _("Access Point configuration is not defined")
                obj.message_post(body=log)
                continue
            try:
                document_type, document_format = None, None
                if invoice_obj.move_type == 'in_invoice':
                    if self.peppol_c5_purchase_inv:
                        document_type = 'purchase-invoices'
                        document_format = 'peppol'
                    elif self.nonpeppol_c5_purchase_inv:
                        document_type = 'purchase-invoices'
                        document_format = 'non-peppol'
                    xml_string = invoice_obj.generate_ubl_xml_string_c5(version=invoice_obj.get_ubl_version())
                elif invoice_obj.move_type == 'in_refund':
                    if self.peppol_c5_purchase_inv:
                        document_type = 'purchase-credit-notes'
                        document_format = 'peppol'
                    elif self.nonpeppol_c5_purchase_inv:
                        document_type = 'purchase-credit-notes'
                        document_format = 'non-peppol'
                    xml_string = invoice_obj.generate_credit_ubl_xml_string_c5(version=invoice_obj.get_ubl_version())
                print("NEW xml_string ===",xml_string)
                    # print("credit xml_string >>>>>>",xml_string)
                base_url = access_point.endpoint
                api_version = access_point.api_version
                client_ref = access_point.get_uuid()
                timeout = self.env['ir.config_parameter'].sudo().get_param('api_timeout', default='20')
                headers = {
                    "Authorization": f"Bearer {access_point.access_token}",
                    "Accept": "application/json",
                }
                files = {
                    'document': (f"{obj.invoice_id.name}.xml", xml_string, 'application/xml')
                }
                print("files>>>>>", files)
                request_url = f"{base_url}/business/{api_version}/iras/submit/{document_type}/{document_format}/{client_ref}"
                try:
                    print('%s/business/%s/%s/%s/%s?????', request_url)
                    response = requests.put(request_url, headers=headers, files=files)
                    print("response",response, response.status_code)
                except requests.exceptions.Timeout:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _(
                        '<b>An Exception has arised.</b><br/>A timeout occured while trying to perform the Send '
                        'Documents API.')
                    obj.message_post(body=log)
                    continue
                except requests.exceptions.HTTPError:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _(
                        '<b>An Exception has arised.</b><br/>HTTP error occurred while trying to perform the Send '
                        'Documents API.')
                    obj.message_post(body=log)
                    continue
                except Exception as e:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _(
                        '<b>An Exception has arised.</b><br/>The Send Documents API is not reachable, please try '
                        'again later.<br/> '
                        'Exception handler details: %s') % (
                              repr(e))
                    obj.message_post(body=log)
                    continue
                status_code = response.status_code
                try:
                    response_data = json.loads(response.text)
                    print("response_data",response_data)
                except:
                    response_data = response.text
                print('\n\n\n\nstatus_code', status_code)
                if status_code == 202 and isinstance(response_data, dict):
                    if obj.invoice_type in ("in_invoice", "in_refund"):
                        obj.write({
                            'state': 'Send Success' if response_data['irasSubmitResponseDto'].get('success') == True else False,
                            'client_ref': response_data.get('clientRef'),
                            'server_receipt': response_data.get('serverReceipt'),
                            'status_message': response_data['irasSubmitResponseDto'].get('message'),
                            'extracted_senderid': response_data['irasSubmitResponseDto'].get('senderId'),
                            'extracted_transmissionid': response_data['irasSubmitResponseDto'].get('transmissionId'),
                            'extracted_acknowledgementid': response_data['irasSubmitResponseDto'].get('acknowledgementId'),
                            'extracted_correlationid': response_data['irasSubmitResponseDto'].get('correlationId'),
                            'extracted_docno': response_data['irasSubmitResponseDto'].get('received'),
                            'progress_type': response_data['irasSubmitResponseDto'].get('progress'),
                            'xml_data': xml_string,
                            'sentapi_json_response': response_data,
                            'document_type': document_type,
                            'document_format': document_format,
                            'errors': response_data['irasSubmitResponseDto'].get('errors') if response_data['irasSubmitResponseDto']['errors'] else False,
                        })
                else:
                    obj.write({'state': 'error', 'xml_data': xml_string})
                    log = _("<b>Send Documents API responded as {} {}</b><br/>{}".format(status_code,
                                                                                         ERROR_RESPONSES_DIC.get(
                                                                                             status_code, ''),
                                                                                         response_data))
                    obj.message_post(body=log)
            except Exception as e:
                print('\n\n\n\ntraceback.format_exc()', traceback.format_exc(), e)
                obj.write({'state': 'error', 'xml_data': xml_string})
                log = _('<b>A Critical Error has arised.</b><br/>Traceback::%s') % (traceback.format_exc())
                obj.message_post(body=log)

    def _check_status(self):
        for obj in self:
            access_point = self.env['peppol.access.point.sg'].sudo().search([('company_id','=',obj.company_id.id)], order="create_date")
            if not access_point:
                obj.write({'state': 'error'})
                log = _("Access Point configuration is not defined")
                obj.message_post(body=log)
                continue
            base_url = access_point.endpoint
            api_version = access_point.api_version
            timeout = self.env['ir.config_parameter'].sudo().get_param('api_timeout', default='20')
            headers = {
                "Authorization": f"Bearer {access_point.access_token}",
                "Accept": "application/json",
            }
            try:
                # response = requests.get(
                #     '%s/business/%s/%s/%s/%s.json' % (base_url, obj.document_type, obj.document_format, api_version, obj.client_ref),
                #     headers=headers)
                # document_type = 'invoices' if obj.invoice_type in ['out_invoice', 'in_invoice'] else 'credit-notes'
                # document_format = 'non-peppol-invoice-2' if obj.invoice_type in ['out_invoice', 'in_invoice'] else 'non-peppol-credit-note-2'
                if obj.is_peppol:
                    document_type = 'invoices' if obj.invoice_type in ['in_invoice'] else 'credit-notes'
                    document_format = 'peppol-invoice-2' if obj.invoice_type in ['in_invoice'] else 'peppol-credit-note-2'
                else:
                    document_type = 'invoices' if obj.invoice_type in ['out_invoice', 'in_invoice'] else 'credit-notes'
                    document_format = 'non-peppol-invoice-2' if obj.invoice_type in ['out_invoice', 'in_invoice'] else 'non-peppol-credit-note-2'
                response = requests.get(
                    '%s/api/business/%s/%s/%s/%s' % (base_url, api_version, document_type, document_format,
                                                     obj.client_ref),
                    headers=headers,
                    timeout=int(timeout))
                print('\nurlllll>>', '%s/api/business/%s/%s/%s/%s' % (base_url, api_version, document_type, document_format,
                                                     obj.client_ref))
                print('\n\n\n\n\n\nreposnse_check_status_method', response, response.status_code)
                logger.error("\n\nurl >>>>>>>>>>>")
                logger.error('%s/business/%s/%s/%s/%s.json' % (base_url, obj.document_type, obj.document_format, api_version, obj.client_ref))
                logger.error("\n\nresponse................")
                logger.error(response)
            except requests.exceptions.Timeout:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>A timeout occured while trying to perform the Check Sent '
                    'Document status Api.')
                obj.message_post(body=log)
                continue
            except requests.exceptions.HTTPError:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>HTTP error occurred while trying to perform the Check Sent '
                    'Document status Api.')
                obj.message_post(body=log)
                continue
            except Exception as e:
                obj.write({'state': 'error'})
                log = _(
                    '<b>An Exception has arised.</b><br/>The Check Document status Api is not reachable, '
                    'please try again later.<br/>Exception handler details: %s') % (repr(e))
                obj.message_post(body=log)
                continue
            status_code = response.status_code
            try:
                response_data = json.loads(response.text)
            except:
                response_data = response.text
            if status_code == 200 and isinstance(response_data, dict):
                if response_data['info'][0].get('status') == 'Send Success':
                    state = response_data['status'] if response_data['status'] == 'Completed' else \
                        response_data['info'][0].get('status')
                else:
                    state = response_data['info'][0].get('status')
                obj.write({'state': state,
                           'status_message': response_data['info'][0].get('statusMessage'),
                           'invalidated': 'yes' if response_data['info'][0].get('invalidated') is True else 'no',
                           'extracted_senderid': response_data['info'][0].get('sender'),
                           'extracted_receiverid': response_data['info'][0].get('receiver'),
                           'extracted_totamount': response_data['info'][0].get('amount'),
                           'extracted_docno': response_data['info'][0].get('documentNo'),
                           'instance_id': response_data['info'][0].get('instanceId'),
                           'iras_status': response_data['info'][0].get('irasStatus'),
                           'iras_statusinfo': response_data['info'][0].get('irasStatusInfo'),
                           'extracted_transmissionid': response_data['info'][0].get('irasTransmissionId'),
                           'extracted_acknowledgementid': response_data['info'][0].get('irasAcknowledgementId'),
                           'docstatusapi_json_response': response_data})
                if self.state == 'Send Success':
                    print('\nself.state', self.state)
                    self.company_id.partner_id.check_gst_register(self.company_id.partner_id)
                    self.partner_id.check_gst_register(self.partner_id)
                    print('\nself.state111111', self.company_id.partner_id.registration_status)
                    print('\nself.state22222', self.partner_id.registration_status)
                    print('\nself.state33333333', self.invoice_id.amount_tax)
                    print('\nself.state', self.env.user.has_group("metro_einvoice_datapost.group_c5_submitter"))
                    if (self.company_id.partner_id.registration_status == 'unregistered' or self.partner_id.registration_status == 'unregistered') and self.invoice_id.amount_tax > 0 and self.env.user.has_group("metro_einvoice_datapost.group_c5_submitter") and self.invoice_id.move_type in ['out_invoice', 'in_invoice']:
                        self.write({'gst_no': self.company_id.partner_id.vat})
            else:
                print("else else")
                obj.write({'state': 'error'})
                print("obj >>>",obj)
                log = _(
                    "Check Document status Api responded with status code: <b>{} {}</b><br/>{}".format(status_code,
                                                                                                            ERROR_RESPONSES_DIC.get(
                                                                                                                status_code,
                                                                                                                ''),
                                                                                                            response_data))
                obj.message_post(body=log)

    def action_retry(self):

        if self.filtered(lambda q: q.state not in 'error,Send Error'.split(',')):
            raise ValidationError(
                _("Please select only 'Error', 'Send Error' & 'Cancelled' queue entries to perform this action."))
        check_status_api = self.filtered(lambda q: q.sent and q.state in ['error'])
        check_status_api._check_status()

        resend_doc_api = self.filtered(lambda q: q.state in ('Send Error', 'error'))
        # if resend_doc_api.peppol_c5_purchase_inv or resend_doc_api.nonpeppol_c5_purchase_inv:
        #     resend_doc_api._send()
        resend_doc_api._c5_send()

    def action_reset(self):
        if self.filtered(lambda q: q.state not in 'error,cancelled'.split(',')):
            raise ValidationError(_("Please select only 'Error' or 'Cancelled' queue entries to perform this action."))
        self.write({'state': 'ready_to_send'})

    def action_cancel(self):
        if self.filtered(lambda q: q.state not in ('ready_to_send', 'error', 'Send Error')):
            raise ValidationError(
                _("Please select only 'Ready to Send' or 'Error' queue entries to perform this action."))
        self.write({'state': 'cancelled'})

    def action_check_status(self):
        if self.filtered(lambda q: q.state not in 'Pending,Processing,Send Success'.split(',')):
            raise ValidationError(
                _("Please select only either of the following states queue entries for this action to perform.\n "
                  "'Pending, Processing and Send Success'. "))
        self._check_status()

    def action_force_cancel(self):
        self.write({'state': 'cancelled'})


    def action_c5_bulk_invoice_send(self):
        if self.filtered(lambda q: q.state != 'ready_to_send'):
            raise ValidationError(_("Please select only 'Ready to Send' queue entries to perform this action."))
        self._bulk_send_c5()

    def action_returns(self, bulk_inv):
        return {
            'type': 'ir.actions.act_window',
            'name': "Peppol Queue C5 Out",
            'res_model': 'peppol.queue.c5.out',
            'view_mode': 'form',
            'view_type': 'form',
            'view_id': self.env.ref('metro_einvoice_datapost.peppol_queue_c5_out_form').id,
            'res_id': bulk_inv.id,
            'target': 'current',
        }

    def _ubl_add_sbd_invoice_header(self):
        """ Creates the StandardBusinessDocumentHeader part of the XML. """
        sbdh_ns = {None: "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader"}
        sbd_root = etree.Element("StandardBusinessDocument", nsmap=sbdh_ns)

        sbd_header = etree.SubElement(sbd_root, "StandardBusinessDocumentHeader")

        # Header Version
        header_version = etree.SubElement(sbd_header, "HeaderVersion")
        header_version.text = "1.0"

        # Sender
        sender = etree.SubElement(sbd_header, "Sender")
        sender_id = etree.SubElement(sender, "Identifier", Authority="iso6523-actorid-upis")
        sender_id.text = self.company_id.partner_id.peppol_identifier

        # Receiver
        receiver = etree.SubElement(sbd_header, "Receiver")
        receiver_id = etree.SubElement(receiver, "Identifier", Authority="iso6523-actorid-upis")
        receiver_id.text = "IRAS"

        #if self.invoice_type == 'out_invoice':
        # Document Identification
        doc_ident = etree.SubElement(sbd_header, "DocumentIdentification")
        standard = etree.SubElement(doc_ident, "Standard")
        standard.text = "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"

        type_version = etree.SubElement(doc_ident, "TypeVersion")
        type_version.text = "2.1"

        access_point = self.env['peppol.access.point.sg'].sudo().search([('company_id', '=', self.company_id.id)],
                                                                        order="create_date")
        instance_identifier = access_point.get_uuid()
        instance_id = etree.SubElement(doc_ident, "InstanceIdentifier")
        instance_id.text = instance_identifier

        doc_type = etree.SubElement(doc_ident, "Type")
        doc_type.text = "Invoice"

        creation_date = etree.SubElement(doc_ident, "CreationDateAndTime")
        creation_date.text = fields.Datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
        # Business Scope
        business_scope = etree.SubElement(sbd_header, "BusinessScope")

        # Scope 1
        scope1 = etree.SubElement(business_scope, "Scope")
        scope1_type = etree.SubElement(scope1, "Type")
        scope1_type.text = "DOCUMENTID"
        scope1_instance = etree.SubElement(scope1, "InstanceIdentifier")
        scope1_instance.text = "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:peppol:pint:billing-1@sg-1:LocalTaxInvoice:sg:1.0::2.1"
        scope1_id = etree.SubElement(scope1, "Identifier")
        scope1_id.text = "peppol-doctype-wildcard"

        # Scope 2
        scope2 = etree.SubElement(business_scope, "Scope")
        scope2_type = etree.SubElement(scope2, "Type")
        scope2_type.text = "PROCESSID"
        scope2_instance = etree.SubElement(scope2, "InstanceIdentifier")
        scope2_instance.text = "urn:peppol:bis:billing"
        scope2_id = etree.SubElement(scope2, "Identifier")
        scope2_id.text = "cenbii-procid-ubl"

        # Scope 3
        transmission_uuid = access_point.get_uuid()
        scope3 = etree.SubElement(business_scope, "Scope")
        scope3_type = etree.SubElement(scope3, "Type")
        scope3_type.text = "Document_UUID"
        scope3_instance = etree.SubElement(scope3, "InstanceIdentifier")
        scope3_instance.text = transmission_uuid
        # if self.invoice_ids:
        #     business_scope = etree.SubElement(sbd_header, "BusinessScope")
        #     # Scope 1
        #     scope3 = etree.SubElement(business_scope, "Scope")
        #     scope3_type = etree.SubElement(scope3, "Type")
        #     scope3_type.text = "Document_UUID"
        #     scope3_instance = etree.SubElement(scope3, "InstanceIdentifier")
        #     scope3_instance.text = transmission_uuid

        return sbd_root, transmission_uuid

    def _ubl_add_sbd_creditnote_header(self):
        """ Creates the StandardBusinessDocumentHeader part of the XML. """
        sbdh_ns = {None: "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader"}
        sbd_root = etree.Element("StandardBusinessDocument", nsmap=sbdh_ns)

        sbd_header = etree.SubElement(sbd_root, "StandardBusinessDocumentHeader")

        # Header Version
        header_version = etree.SubElement(sbd_header, "HeaderVersion")
        header_version.text = "1.0"

        # Sender
        sender = etree.SubElement(sbd_header, "Sender")
        sender_id = etree.SubElement(sender, "Identifier", Authority="iso6523-actorid-upis")
        sender_id.text = self.company_id.partner_id.peppol_identifier

        # Receiver
        receiver = etree.SubElement(sbd_header, "Receiver")
        receiver_id = etree.SubElement(receiver, "Identifier", Authority="iso6523-actorid-upis")
        receiver_id.text = "IRAS"

        # Document Identification
        doc_ident = etree.SubElement(sbd_header, "DocumentIdentification")
        standard = etree.SubElement(doc_ident, "Standard")
        standard.text = "urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2"

        type_version = etree.SubElement(doc_ident, "TypeVersion")
        type_version.text = "2.1"

        access_point = self.env['peppol.access.point.sg'].sudo().search([('company_id', '=', self.company_id.id)],
                                                                        order="create_date")
        instance_identifier = access_point.get_uuid()
        instance_id = etree.SubElement(doc_ident, "InstanceIdentifier")
        instance_id.text = instance_identifier

        doc_type = etree.SubElement(doc_ident, "Type")
        doc_type.text = "CreditNote"

        creation_date = etree.SubElement(doc_ident, "CreationDateAndTime")
        creation_date.text = fields.Datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
        # Business Scope
        business_scope = etree.SubElement(sbd_header, "BusinessScope")

        # Scope 1
        scope1 = etree.SubElement(business_scope, "Scope")
        scope1_type = etree.SubElement(scope1, "Type")
        scope1_type.text = "DOCUMENTID"
        scope1_instance = etree.SubElement(scope1, "InstanceIdentifier")
        scope1_instance.text = "urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2::CreditNote##urn:peppol:pint:billing-1@sg-1:LocalTaxInvoice:sg:1.0::2.1"
        scope1_id = etree.SubElement(scope1, "Identifier")
        scope1_id.text = "peppol-doctype-wildcard"

        # Scope 2
        scope2 = etree.SubElement(business_scope, "Scope")
        scope2_type = etree.SubElement(scope2, "Type")
        scope2_type.text = "PROCESSID"
        scope2_instance = etree.SubElement(scope2, "InstanceIdentifier")
        scope2_instance.text = "urn:peppol:bis:billing"
        scope2_id = etree.SubElement(scope2, "Identifier")
        scope2_id.text = "cenbii-procid-ubl"

        # Scope 3
        crd_transmission_uuid = access_point.get_uuid()
        scope3 = etree.SubElement(business_scope, "Scope")
        scope3_type = etree.SubElement(scope3, "Type")
        scope3_type.text = "Document_UUID"
        scope3_instance = etree.SubElement(scope3, "InstanceIdentifier")
        scope3_instance.text = crd_transmission_uuid

        return sbd_root, crd_transmission_uuid

    def _c5_send(self):
        sbd_root_invoice, transmission_uuid = self._ubl_add_sbd_invoice_header()
        sbd_root_creditnote, crd_transmission_uuid = self._ubl_add_sbd_creditnote_header()

        has_invoice_peppol = False
        has_invoice_nonpeppol = False
        has_creditnote_peppol = False
        has_creditnote_nonpeppol = False

        invoice_ids = self.invoice_ids if self.invoice_ids else self.invoice_id
        for invoice_obj in invoice_ids:
            print("invoice_obj.move_type ==", invoice_obj.move_type)
            access_point = self.env['peppol.access.point.sg'].sudo().search([('company_id', '=', self.company_id.id)],
                                                                            order="create_date")
            if not access_point:
                self.write({'state': 'error'})
                log = _("Access Point configuration is not defined")
                self.message_post(body=log)
                continue

            # this line uncomment before deploy
            is_peppol = invoice_obj.verify_partner_peppol_identifier(invoice_obj.partner_id)
            if invoice_obj.move_type in ['out_invoice', 'in_invoice']:
                invoice_xml = invoice_obj.generate_c5_bulk_invoice_ubl_xml_etree(version=invoice_obj.get_ubl_version(), transmission_uuid=transmission_uuid)
                print('\ninvoice_xml', invoice_xml)
                sbd_root_invoice.append(invoice_xml)
                if is_peppol:
                    has_invoice_peppol = True
                else:
                    has_invoice_nonpeppol = True
            elif invoice_obj.move_type in ['out_refund', 'in_refund']:
                invoice_xml = invoice_obj.generate_c5_bulk_credit_ubl_xml_etree(version=invoice_obj.get_ubl_version(), transmission_uuid=crd_transmission_uuid)
                sbd_root_creditnote.append(invoice_xml)
                if is_peppol:
                    has_creditnote_peppol = True
                else:
                    has_creditnote_nonpeppol = True

        if has_invoice_peppol:
            xml_string = etree.tostring(
                sbd_root_invoice, pretty_print=True, encoding="UTF-8", xml_declaration=True
            )
            print('\n\n\n\n\n\nxml_string_in', xml_string)
            document_type = 'purchase-invoices'
            document_format = 'peppol'
        elif has_invoice_nonpeppol:
            xml_string = etree.tostring(
                sbd_root_invoice, pretty_print=True, encoding="UTF-8", xml_declaration=True
            )
            print('\n\n\n\n\n\nxml_string_in', xml_string)
            document_type = 'purchase-invoices' if invoice_obj.move_type == 'in_invoice' else 'invoices'
            document_format = 'non-peppol'
        if has_creditnote_peppol:
            xml_string = etree.tostring(
                sbd_root_creditnote, pretty_print=True, encoding="UTF-8", xml_declaration=True
            )
            print('\n\n\n\n\n\nxml_string_cre', xml_string)
            document_type = 'purchase-credit-notes'
            document_format = 'peppol'
        elif has_creditnote_nonpeppol:
            xml_string = etree.tostring(
                sbd_root_creditnote, pretty_print=True, encoding="UTF-8", xml_declaration=True
            )
            print('\n\n\n\n\n\nxml_string_cre', xml_string)
            document_type = 'purchase-credit-notes' if invoice_obj.move_type == 'in_refund' else 'credit-notes'
            document_format = 'non-peppol'

        try:
            base_url = access_point.endpoint
            api_version = access_point.api_version
            client_ref = access_point.get_uuid()
            timeout = self.env['ir.config_parameter'].sudo().get_param('api_timeout', default='20')
            headers = {
                "Authorization": f"Bearer {access_point.access_token}",
                "Accept": "application/json",
            }
            files = {
                'document': (f"{self.id}.xml", xml_string, 'application/xml')
            }
            print("files>>>>>", files)
            # request_url = f"{base_url}/business/{api_version}/iras/submit/{document_type}/{document_format}/{client_ref}"
            request_url = f"{base_url}/api/submit/{document_type}/{document_format}/{client_ref}"
            try:
                print('%s/business/%s/%s/%s/%s?????', request_url)
                response = requests.post(request_url, headers=headers, files=files)
                print("response", response, response.status_code)
            except requests.exceptions.Timeout:
                self.write({'state': 'error', 'xml_data': xml_string})
                log = _(
                    '<b>An Exception has arised.</b><br/>A timeout occured while trying to perform the Send '
                    'Documents API.')
                self.write({'state': 'error', 'xml_data': xml_string, 'errors': log})
                self.message_post(body=log)
                return
            except requests.exceptions.HTTPError:
                self.write({'state': 'error', 'xml_data': xml_string})
                log = _(
                    '<b>An Exception has arised.</b><br/>HTTP error occurred while trying to perform the Send '
                    'Documents API.')
                self.write({'state': 'error', 'xml_data': xml_string, 'errors': log})
                self.message_post(body=log)
                return
            except Exception as e:
                self.write({'state': 'error', 'xml_data': xml_string})
                log = _(
                    '<b>An Exception has arised.</b><br/>The Send Documents API is not reachable, please try '
                    'again later.<br/> '
                    'Exception handler details: %s') % (
                          repr(e))
                self.write({'state': 'error', 'xml_data': xml_string, 'errors': log})
                self.message_post(body=log)
                return
            status_code = response.status_code
            try:
                response_data = json.loads(response.text)
                print("response_data", response_data)
            except:
                response_data = response.text
            print('\n\n\n\nstatus_code', status_code)
            if status_code == 200 and isinstance(response_data, dict):
                get_response_submit = response_data['irasSubmitResponseDto'][0]
                print('\nget_response_submit', get_response_submit)
                self.write({
                    'state': 'Send Success' if get_response_submit.get('success') == True else False,
                    'client_ref': response_data.get('clientRef'),
                    'server_receipt': response_data.get('serverReceipt'),
                    'status_message': get_response_submit.get('message'),
                    'extracted_senderid': get_response_submit.get('senderId'),
                    'extracted_transmissionid': get_response_submit.get('transmissionId'),
                    'extracted_acknowledgementid': get_response_submit.get('acknowledgementId'),
                    'extracted_correlationid': get_response_submit.get('correlationId'),
                    'extracted_docno': get_response_submit.get('received'),
                    'progress_type': get_response_submit.get('progress'),
                    'xml_data': xml_string,
                    'sentapi_json_response': response_data,
                    'document_type': document_type,
                    'document_format': document_format,
                    'error_code': get_response_submit.get('errorCode') if
                    get_response_submit['errorCode'] else False,
                    'errors': get_response_submit.get('errors') if
                    get_response_submit['errors'] else False,
                    'is_peppol': is_peppol,
                })
            else:
                self.write({'state': 'error', 'xml_data': xml_string})
                log = _("<b>Send Documents API responded as {} {}</b><br/>{}".format(status_code,
                                                                                     ERROR_RESPONSES_DIC.get(
                                                                                         status_code, ''),
                                                                                     response_data))
                self.write({'state': 'error', 'xml_data': xml_string, 'errors': log})
                self.message_post(body=log)
                return
        except Exception as e:
            print('\n\n\n\ntraceback.format_exc()', traceback.format_exc(), e)
            self.write({'state': 'error', 'xml_data': xml_string})
            log = _('<b>A Critical Error has arised.</b><br/>Traceback::%s') % (traceback.format_exc())
            self.write({'state': 'error', 'xml_data': xml_string, 'errors': log})
            self.message_post(body=log)









        # print("_send() >>>>>")
        # sbd_root = self._ubl_add_sbd_header()
        # print('\n\n\n\n\nsbd_root', sbd_root)
        # # invoice_root = etree.Element("Invoices")
        # # creditnote_root = etree.Element("CreditNotes")
        # has_invoice = False
        # has_creditnote = False
        # xml_string = ''
        # invoice_ids = self.invoice_ids if self.invoice_ids else self.invoice_id
        # for invoice_obj in invoice_ids:
        #     print("invoice_obj.move_type ==", invoice_obj.move_type)
        #     access_point = self.env['peppol.access.point.sg'].sudo().search([('company_id', '=', self.company_id.id)],
        #                                                                     order="create_date")
        #     if not access_point:
        #         self.write({'state': 'error'})
        #         log = _("Access Point configuration is not defined")
        #         self.message_post(body=log)
        #         continue
        #
        #     if invoice_obj.move_type == 'out_invoice':
        #         invoice_xml = invoice_obj.generate_c5_bulk_invoice_ubl_xml_etree(version=invoice_obj.get_ubl_version())
        #         sbd_root.append(invoice_xml)
        #         has_invoice = True
        #     else:
        #         creditnote_xml = invoice_obj.generate_c5_bulk_credit_ubl_xml_etree(
        #             version=invoice_obj.get_ubl_version())
        #         sbd_root.append(creditnote_xml)
        #         has_creditnote = True
        #
        # if has_invoice:
        #     xml_string = etree.tostring(
        #         sbd_root, pretty_print=True, encoding="UTF-8", xml_declaration=True
        #     )
        #     print('\n\n\n\n\n\nxml_string_in', xml_string)
        #     document_type = 'invoices'
        #     document_format = 'peppol'
        # elif has_creditnote:
        #     xml_string = etree.tostring(
        #         sbd_root, pretty_print=True, encoding="UTF-8", xml_declaration=True
        #     )
        #     print('\n\n\n\n\n\nxml_string_cre', xml_string)
        #     document_type = 'credit-notes'
        #     document_format = 'non-peppol'
        #
        # try:
        #     base_url = access_point.endpoint
        #     api_version = access_point.api_version
        #     client_ref = access_point.get_uuid()
        #     timeout = self.env['ir.config_parameter'].sudo().get_param('api_timeout', default='20')
        #     headers = {
        #         "Authorization": f"Bearer {access_point.access_token}",
        #         "Accept": "application/json",
        #     }
        #     files = {
        #         'document': (f"{self.id}.xml", xml_string, 'application/xml')
        #     }
        #     print("files>>>>>", files)
        #     request_url = f"{base_url}/business/{api_version}/iras/submit/{document_type}/{document_format}/{client_ref}"
        #     try:
        #         print('%s/business/%s/%s/%s/%s?????', request_url)
        #         response = requests.put(request_url, headers=headers, files=files)
        #         print("response", response, response.status_code)
        #     except requests.exceptions.Timeout:
        #         self.write({'state': 'error', 'xml_data': xml_string})
        #         log = _(
        #             '<b>An Exception has arised.</b><br/>A timeout occured while trying to perform the Send '
        #             'Documents API.')
        #         self.message_post(body=log)
        #         return
        #     except requests.exceptions.HTTPError:
        #         self.write({'state': 'error', 'xml_data': xml_string})
        #         log = _(
        #             '<b>An Exception has arised.</b><br/>HTTP error occurred while trying to perform the Send '
        #             'Documents API.')
        #         self.message_post(body=log)
        #         return
        #     except Exception as e:
        #         self.write({'state': 'error', 'xml_data': xml_string})
        #         log = _(
        #             '<b>An Exception has arised.</b><br/>The Send Documents API is not reachable, please try '
        #             'again later.<br/> '
        #             'Exception handler details: %s') % (
        #                   repr(e))
        #         self.message_post(body=log)
        #         return
        #     status_code = response.status_code
        #     try:
        #         response_data = json.loads(response.text)
        #         print("response_data", response_data)
        #     except:
        #         response_data = response.text
        #     print('\n\n\n\nstatus_code', status_code)
        #     if status_code == 202 and isinstance(response_data, dict):
        #         self.write({
        #             'state': 'Send Success' if response_data['irasSubmitResponseDto'].get('success') == True else False,
        #             'client_ref': response_data.get('clientRef'),
        #             'server_receipt': response_data.get('serverReceipt'),
        #             'status_message': response_data['irasSubmitResponseDto'].get('message'),
        #             'extracted_senderid': response_data['irasSubmitResponseDto'].get('senderId'),
        #             'extracted_transmissionid': response_data['irasSubmitResponseDto'].get('transmissionId'),
        #             'extracted_acknowledgementid': response_data['irasSubmitResponseDto'].get('acknowledgementId'),
        #             'extracted_correlationid': response_data['irasSubmitResponseDto'].get('correlationId'),
        #             'extracted_docno': response_data['irasSubmitResponseDto'].get('received'),
        #             'progress_type': response_data['irasSubmitResponseDto'].get('progress'),
        #             'xml_data': xml_string,
        #             'sentapi_json_response': response_data,
        #             'document_type': document_type,
        #             'document_format': document_format,
        #             'errors': response_data['irasSubmitResponseDto'].get('errors') if
        #             response_data['irasSubmitResponseDto']['errors'] else False,
        #         })
        #
        #     else:
        #         self.write({'state': 'error', 'xml_data': xml_string})
        #         log = _("<b>Send Documents API responded as {} {}</b><br/>{}".format(status_code,
        #                                                                              ERROR_RESPONSES_DIC.get(
        #                                                                                  status_code, ''),
        #                                                                              response_data))
        #         self.message_post(body=log)
        #         return
        # except Exception as e:
        #     print('\n\n\n\ntraceback.format_exc()', traceback.format_exc(), e)
        #     self.write({'state': 'error', 'xml_data': xml_string})
        #     log = _('<b>A Critical Error has arised.</b><br/>Traceback::%s') % (traceback.format_exc())
        #     self.message_post(body=log)
