# -*- coding: utf-8 -*-
{
    'name': 'WhatsApp Integration',
    'summary': "Whatsapp Integration",
    'author': 'Metro Group Solutions',
    'website': 'https://metrogroup.solutions/',
    'category': 'Technical',
    'version': '14.0.0.1.0',
    'depends': [
        'web',
        'sale',
        'portal',
        'web_ir_actions_act_multi',
        'base',
        'account',
        'purchase',
        'stock',
        'metroerp_customizations',
        'metroerp_progressive_billing',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/demo_data.xml',
        'data/ir_cron_data.xml',
        'views/share_action.xml',
        'views/assistro_whatsapp_template_views.xml',
        'views/res_config_settings.xml',
        'views/sale_order_inherited_views.xml',
        'views/account_move_views.xml',
        'views/stock_picking_views.xml',
        'views/purchase_order_views.xml',
        'views/whatsapp_log_views.xml',
        'views/account_payment_views.xml',
        'wizard/whatsapp_composer_views.xml',
        'wizard/whatsapp_placeholder_views.xml',
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
